### ISSUE TITLE
request: exclude some files from pagination

### ISSUE THREAD

**Issue by item4** [lektor/lektor#10]
If I have these(see below) structure and add sitemap with [this guide](https://www.getlektor.com/docs/guides/sitemap/), my list must include `sitemap.xml`.
- `content/contents.lr`

```
_model: blog

```
- `models/blog.ini`

``` ini
[model]
name = Blog
label = Blog
hidden = yes

[children]
model = blog-post
order_by = -pub_date, title
slug_format = {{ this.pub_date|dateformat('YYYY-MM-dd') }}/{{ this.title }}/

[pagination]
enabled = yes
per_page = 1
```

How can I **pop** `sitemap.xml` or some files (like keybase proof) from pagination? (Currently I make simple sitemap build package to avoid this problem)

**Comment by mitsuhiko** [comment]
Yeah. That's something I want to do. This does not just affect pagination but general items that should not be included by children. This would also be useful for allowing pages to be generated but not appear to be discovered.  Right now you can set a page to `_hidden` but that will make it not generate at all.

Need a name for this key. Maybe `_reachable: no` or something?

**Comment by item4** [comment]
How about this way?

``` ini
[pagination]
include_key = _reachable
```

or

``` ini
[pagination]
exclude_key = _no_paging
```

**Comment by mitsuhiko** [comment]
@item4 that would not even be necessary because the pagination would exclude this automatically.  The pagination is based on the children and I want to be able to exclude things from children (which is what `_hidden: yes` already does) but still allow generation.  This is a pretty minor change but I need to figure out the name for the field :)

**Comment by mitsuhiko** [comment]
Maybe `_discoverable: no`?

**Comment by mitsuhiko** [comment]
Secondly however, yes, there probably also needs to be a way to let the pagination work on other queries than just the normal children of the page.

**Comment by mitsuhiko** [comment]
So basically to give this more context I think the problem is that right now lektor assumes a bit that you have something like a blog under a certain path if you also have other pages on the same level that follow a different model. So what you probably want to have is the ability to set the pagination to only consider a certain model.  Maybe something like this:

``` ini
[pagination]
items = this.children.filter(F._model == 'blog-post')
```

**Comment by item4** [comment]
:+1: for both, `_discoverable: no` and `items = this.children.filter(F._model == 'blog-post')`

**Comment by mitsuhiko** [comment]
`master` branch has `_discoverable` now.  If you set `_discoverable: no` in a file (or untick the corresponding checkbox in the admin) a page is still being built but no longer picked up by `.children`.

**Comment by mitsuhiko** [comment]
This is implemented now.
