### ISSUE TITLE
Add a preview feature to the edit page

### ISSUE THREAD

**Issue by cav71** [lektor/lektor#1014]
Hi,
I wonder if it is possible to add a feature to the editor page:
![image](https://user-images.githubusercontent.com/2042971/158026056-f4212009-e9f1-4647-bcb5-2b187b3f1cf1.png)

Ideally this is similar to how GitHub works.
I can go ahead and implement it but Id' like to understand if there's some solution out there doing this (it would be quite.a killer feature).

**Comment by dairiki** [comment]
I think it will be a little tricky to implement a markup-field-level preview like this.  Here's why I think that.

The contents of each Lektor markup field get incorporated (or not) into the final HTML output in various ways as determined by the project's templates.  That HTML then gets styled by the project's CSS.  (Both the templates and the CSS are typically not provided directly by Lektor, but are customized for each particular project.)  By way of contrast, on GitHub, github specifies how the markdown gets displayed in the final HTML, so it knows how to format a preview, too.
Correctly rendering a preview depends not only on the (project-specific) site CSS file but on the context into which that markup field will be rendered.  In the general case, to get a field-specific preview to look like what the final output will look like would require implementing something like a way to specify custom preview CSS for each field — that's not too hard to implement, but seems like would be quite a pain to actually use.

The Lektor admin GUI does provide two ways to preview changes: either in an iframe, or by browsing to the resulting page.  (Keep in mind that hitting the "Save" button in the admin interface just save the changes to the local source, not to the published web site.  So requiring a "save" to "preview" the changes isn't really a big hardship.)

![image](https://user-images.githubusercontent.com/495018/158028344-fc997693-f35e-4dd7-ab0c-53252da60bf9.png)

**Comment by cav71** [comment]
I was thinking something a bit more trivial eg:
* user click on the "preview" tab
* this trigger a server side round trip to a "render" method posting txt and returning the html to be rendered in the tab
If I understand it right I need:
1. modify the js app 
2 add a render method to the admin Flask app

**Comment by dairiki** [comment]
@cav71 Yes, that would work to get the HTML into a preview panel. And it sounds like you have a good understanding of what's required to implement it.  There are some fiddly details that might have to be addressed.  (E.g. Markdown rendering in Lektor is "context"-dependent — where "context" most means which output page is being rendered — so that links can be resolved/relativized correctly.  Careful attention would have to be paid to that bit to avoid broken links in the preview.)

But my point is, at that point, that HTML will be styled according to the Admin UI stylesheet, not the stylesheet for the published site — so, in most cases, it won't look all that similar to the final finished product when published.  Given that limitation, I'm not sure that it's worth the effort.  Either of the other two means of previewing the whole page (circled in my screenshot) do style the page with the final, as-published, CSS and so do provide a good preview of the finished product.
