### ISSUE TITLE
css non updating in live server

### ISSUE THREAD

**Issue by andrearicci** [lektor/lektor#1037]
I noticed that some modification to the css are not shown while developing the site: I added a class in the html, stilzed the class in the css, but it doesn't show up (also checked ctrl+12). 

If I build the site, there it is, the css is complete as expected. it seems that `lektor server` doesn't build the css

![lektor server](https://user-images.githubusercontent.com/1193266/173229023-a9ec2a95-290e-4e9a-ae00-3ae79a2d4cb6.png)

this is a screenshot of the missing styling in lektor server

![local build](https://user-images.githubusercontent.com/1193266/173228958-380fe297-b165-4d28-977b-5d8fbe88894e.png)

this is a screenshot of the correct styling when I build the site.

Lektor, version 3.3.4 on firefox 101.0.1 - win 10

**Comment by dairiki** [comment]
I'm afraid that I don't fully understand what the issue is.  Can you be more specific about where your `style.css` is coming from?

Is it in the Lektor project's [assets/](https://www.getlektor.com/docs/project/structure/#assets/)?  If so `lektor server` should be able to serve it.

**Comment by andrearicci** [comment]
Hi, thank you for answering.
My CSS are in \assets\static
This is what my standard pages are loading:
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
<!-- Milligram CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">
<!-- You should properly set the path from the main file. -->
<link rel="stylesheet" href="{{ '/static/style.css'|url }}">
```
and of course my modification on the milligram's defaults resides in _style.css_.

`lektor server' desn't pass all the styles, while I get all of them on the builded site.  As an exhample  this rule:
```
p>img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  max-width: auto;
  width: auto;
}
```

does not work locally (all images are left- justified) , but works fine on the final website, like in https://andrearicci.it/howtocad/blog/scala-di-stampa/

The missmatch is there even if I force a cache clean reload.

**Comment by dairiki** [comment]
I am not sure what's going on.  I can not reproduce the issue here (Linux).

Perhaps you are encountering a Windows-specific issue, or there is something else going on.
I'm sorry, but I don't have a convenient Windows machine to test on, at the moment.
I will try the quickstart on Windows when I get a chance.

If you could share a complete Lektor project which demonstrates the issue, that *might* help.

-----

Here's what I did here to try to replicate.
```shell
$ lektor --version
> Lektor, version 3.3.5

$ lektor quickstart --name statictest
# Accept all the default answers
> Lektor Quickstart
> =================
>  [...]
> That's all. Create project? [Y/n] 

$ cd statictest

$ lektor server
> * Project path: [...]
[...]
> * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
```

Note that the quickstart [`templates/layout.html`][layout.html] includes a CSS file exactly like you do
```html+jinja
<link rel="stylesheet" href="{{ '/static/style.css'|url }}">
```
Next I pointed my browser at http://localhost:5000/ and saw:
![image](https://user-images.githubusercontent.com/495018/180671384-1c249aa5-ce0a-48bc-9c77-2a8045ec53b0.png)

Then, in a new terminal:
```shell
$ cd statictest

$ echo 'body { color: red; }' >> assets/static/style.css
```

Finally, I had to \<ctl\>-R reload my browser to see
![image](https://user-images.githubusercontent.com/495018/180671318-ad2c7f9a-c415-41c1-9ceb-58ef617230e1.png)

[layout.html]: https://github.com/lektor/lektor/blob/d52cb2a16d51ee1f55080590d396523b8a145bb0/lektor/quickstart-templates/project/templates/layout.html.in#L3

**Comment by andrearicci** [comment]
in Lektor, version 3.4.0b8, I don't have the issue
