### ISSUE TITLE
[Build] Missing frontend assets when building from the source

### ISSUE THREAD

**Issue by frostming** [lektor/lektor#1081]
Currently, the frontend assets are missing if we install from a Git URL or zipball provided by GitHub. This is because we build the frontend files in a Makefile and it is called when publishing to PyPI.

~~Plus, are you open to switching to [hatch](https://hatch.pypa.io) as the build backend?~~
Oh, you are already doing it!

**Comment by dairiki** [comment]
As you note, I started to play with using hatch including using a custom build hook to build the frontend. That work is in PR #1082.

I agree that it's definitely a win to hook the frontend build into the PEP517 build process.  I'm not totally convinced that hatch is the best option for doing this, but it does work.  (I haven't looked at PDM carefully yet, but that may be another option?)

[edited to link to PR rather than directly to my working branch]
