### ISSUE TITLE
Custom Field Type ignores `addon_label`

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#1089]
Consider the example below, I would expect the label to show the text "hi" but instead Lektor only prints "0".
If I replace the type "test" with "integer" it works as expected.

Model:
```ini
[fields.why]
type = test
addon_label = hi
```

Python custom `lektor.types.base.Type`:
```py
class TestType(Type):
    widget = 'integer'

    def value_from_raw(self, raw: 'RawValue') -> int:
        return int(raw.value or '0')

[...]
self.env.add_type(TestType)
```

**Comment by dairiki** [comment]
It looks like the parsing of the `addon_label` option (in order to pass it on to the Admin frontend) happens in [`SingleInputType.to_json`](https://github.com/lektor/lektor/blob/fcf31cb620989715fd0773a8d50abf8ee554f546/lektor/types/primitives.py#L14).

I suspect that if you changed your custom type (`TestType`) to inherit from `lektor.types.primitives.SingleInputType` instead of `lektor.types.base.Type`, your `addon_label` would work as expected.

**Comment by relikd** [comment]
Indeed it does.

Is that something that should be fixed in code or mentioned in the documentation?

**Comment by dairiki** [comment]
I think it's probably a documentation issue.

It appears that only some of the Admin UI widget types support addon_labels.

In particular, only the `singleline-text`, `integer`, `float`, `datepicker`, `slug`, and `url` widgets support addon_text.  The built-in types that use these widgets all inherit from `SingleInputType`.
(The `flow`, `multiline-text`, `select`, `checkboxes`, and `checkbox` widgets do not support addon_text.)

I suppose we could add a rubric about this in the [Adding New Field Types](https://www.getlektor.com/docs/plugins/howto/#adding-new-field-types) section of the documentation.

**Comment by relikd** [comment]
And also here https://www.getlektor.com/docs/api/db/type/, where the "wrong" type is used.

**Comment by dairiki** [comment]
I've just opened lektor/lektor-website#357 to track this.

Closing this ticket...
