### ISSUE TITLE
Installation doesn't install required pytz

### ISSUE THREAD

**Issue by bockstaller** [lektor/lektor#1109]
Installing lektor via pipx and pip doesn't install the required dependency pytz.
It is imported in the code and in lektors setup.cfg, but as far as I can tell it isn't included in the wheel or the metadata of the source distribution.

**Comment by ZakiChammaa** [comment]
I have the same problem. It was working fine yesterday.

**Comment by dairiki** [comment]
Thank you for the report.

I believe this only affects the 3.3 (stable) branch, where we (erroneously) do not list `pytz` as a dependency.

Up until recently, the `babel` package depended unconditionally on `pytz`, so it was being installed transitively.  Since `babel==2.12.0` (published 9 hours ago), `pytz` is only a conditional dependency (python-babel/babel#940) so only gets pulled in for python<3.9.

**Comment by dairiki** [comment]
Fixed in [release 3.3.8](https://github.com/lektor/lektor/releases/tag/v3.3.8).

**Comment by CAM-Gerlach** [comment]
(For reference: The previous fix for 3.4.x was PR #1036)

**Comment by dairiki** [comment]
> (For reference: The previous fix for 3.4.x was PR #1036)

@CAM-Gerlach Unfortunately, that PR never made it into the 3.3-maintenance branch.  And, thank you for pointing that out, because now I see that the rest of that PR did not make it into 3.3-maintenance either. :-/

**Comment by CAM-Gerlach** [comment]
Yup, that's what I figured. (BTW, FWIW noticed this as part of releasing the updated Lektor 3.3.8 Conda-Forge packages in conda-forge/lektor-feedstock#23 ).
