### ISSUE TITLE
dateformat filter causes assertion errors

### ISSUE THREAD

**Issue by kno10** [lektor/lektor#1121]
If you define a date field, but leave it empty, then use the `|dateformat` filter, the page fails to render with an assertion error.
This caused me to look for a error in the template until I figured out that one alternative of one item did not have a proper date set.

This cannot be caught easily. I had tried `{{ this.datefield|dateformat or this.datefield }}`  as a fallback, but this still causes the exception; in the end I put the obvious `{% if this.datefield %}` around the entire tag. But I would like something more robust, probably some `is_valid_date` function?

**Comment by dairiki** [comment]
Thank you for the report.

Currently, `dateformat` is essentially just `babel.dates.format_date`, with a shim to fill in the `locale` parameter.  Babel simply [assumes](https://github.com/python-babel/babel/blob/134c792df3b6aa84de3e74e81a875493c95dcc2e/babel/dates.py#L676) the input is either a `date`, `datetime` or `None` (meaning current date).

When a date field is left empty, its value in jinja-land is an instance of `jinja2.Undefined`.  When the `Undefined` is passed to `babel.dates.format_date` it eventually trips [this assert](https://github.com/python-babel/babel/blob/134c792df3b6aa84de3e74e81a875493c95dcc2e/babel/dates.py#L1326).

I think the fix is to update our `dateformat` filter (and its friends `timeformat` and `datetimeformat`) to check the type of its argument and raise `TypeError` when they are not of an expected type.
If passed an `Undefined` instance, these filters should probably return `None` — or maybe just return the same `Undefined` instance [eta: or maybe an empty string?] — either of those options would allow your `{{ this.datefield|dateformat or "no date" }}` (or `{{ this.datefile|dateformat|default("—")  }}`) to work.

See the [implementation](https://github.com/pallets/jinja/blob/9dad679695ccf84f06f8df897a6c5908e1963363/src/jinja2/filters.py#L221) of jinja's `items` filter for an example of how jinja handles a similar case.

**Comment by dairiki** [comment]
On second thought, `dateformat` and friends, when passed an `Undefined`, should return that undefined value coerced to a `str`.  Effectively, that results in returning an empty string, or — if passed a `StrictUndefined` — a `jinja2.exceptions.UndefinedError` being raised.
