### ISSUE TITLE
Inflight NPM dependency deprecated

### ISSUE THREAD

**Issue by berlincount** [lektor/lektor#1205]
as per today:

```
~/src/github.com/lektor/lektor$ make
---> installing npm dependencies
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
...
```

**Comment by webknjaz** [comment]
It might be a good idea to set up Dependabot in the repo, then. Although, I'd recommend configuring infrequent updates since daily notifications are very noisy.

**Comment by dairiki** [comment]
As a general note, since our target is a JS frontend which is used only for a local GUI (run on localhost) we are not as concerned about XSS injection vulnerabilities as some might be.  That said, it's always good to be up-to-date.

Looking closer at the specific warnings:

- The deprecated versions of `glob` and `inflight` are transitive dependencies from `mocha` and `nyc`. We appear (via `npm install`) to be running the latest versions of those (mocha@10.8.2 and nyc@17.1.0).
- The `@humanwhocodes` deprecations are transitive from `eslint`.  We are on eslint 8.x, the latest release 9.14.0. Upgrading, however, involves upgrading a number of eslint-plugins (and may be above my pay grade).
- The deprecated `rimraf` is a transitive dep of `eslint` as well as `nyc`.

All of these deprecation warnings seem only to affect tools we use for linting and unit-testing.  As such, security risks seem minimal.

----

Mostly unrelated: when building with sass versions greater than 1.77.6 a number of deprecation warnings are emitted.  A good number are triggered by bootstrap code (see twbs/bootstrap#40849).
Some are due to our use of the deprecated `@import` (but bootstrap currently uses `@import`, too.)

----

@yagebu Have you got any wisdom to add?

**Comment by yagebu** [comment]
I' ll create a PR to update the frontend dependencies, but as @dairiki stated above, these deprecated versions (as they usually do) come from some development dependencies and aren't really anything to worry about.
