### ISSUE TITLE
File mask for build artifacts 

### ISSUE THREAD

**Issue by narun4sk** [lektor/lektor#1213]
```
> ls -l build/*
-rw------- 1 xyz xyz 20451 Nov 26 00:08 build/index.html

build/de:
total 24
-rw------- 1 xyz xyz 20518 Nov 26 00:08 index.html

build/static:
total 16
drwxr-xr-x  2 xyz xyz 4096 Nov 26 00:03 css/
drwxr-xr-x  2 xyz xyz 4096 Nov 26 00:03 img/
drwxr-xr-x  2 xyz xyz 4096 Nov 26 00:03 js/
```

Looks like currently directories are created with the convenient `drwxr-xr-x` permissions, files however are assigned `read`/`write` only to the user `-rw-------`. In my case it would be much more convenient, if file group would also have the same or just the read permission: `-rw-r-----`.

I've managed to achieve the desired effect with the following plugin:
```
from lektor.pluginsystem import Plugin
from pathlib import Path


class UmaskPlugin(Plugin):
    name = 'umask'
    description = "640 permissions on output files."

    def on_after_build(self, prog, **extra):
        filemode = "640"
        artifact = prog.primary_artifact
        if not artifact:
            return
        path = Path(artifact.dst_filename)
        if path.is_file():
            path.chmod(int(filemode, 8))
```

But despite my great success, I guess ideally there should be `umask` setting within the `Project File`, so that users may choose whatever works best for them? :thinking:

**Comment by dairiki** [comment]
I think I remember that I stumbled across this, too.  And I think I have a fix for it.
But my fix is on my computer at home, and I'm currently on the road.

I can look at this next week.

**Comment by dairiki** [comment]
The issue is related to the use of `[tempfile.mkstemp][mkstemp]` to create new files.  `Mkstemp` always creates files that are only accessible by the creating user.

In the case reported here, the usage of `mkstemp` causing the issues is [here](https://github.com/lektor/lektor/blob/c22e224ec56620c2a1d90016d74518970b1dd578/lektor/builder.py#L728-L731).  There is another usage [here](https://github.com/lektor/lektor/blob/c22e224ec56620c2a1d90016d74518970b1dd578/lektor/utils.py#L527-L529) which creates a similar issue for `contents.lr` files edited via the admin GUI.


The issue is complicated by the fact that it seems difficult to determine the current *umask* in a thread-safe way without creating a file.  (The current value of the umask is available from [os.umask], but using that involves temporarily setting a new umask.)


One solution may be:
1. Read the current umask once at startup.  Maybe make this available from the Environment.
2. [Chmod](https://docs.python.org/3/library/os.html#os.chmod) files opened via `mkstemp` appropriately.

Open question:
- When replacing an existing file, should we duplicate the permissions of the existing file?

[mkstemp]: https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp
[os.umask]: https://docs.python.org/3/library/os.html#os.umask

**Comment by etoimene** [comment]
> Open question:
> 
>     * When replacing an existing file, should we duplicate the permissions of the existing file?

I would say yes.
On the other hand, I don't see a point in having different permissions on different files in this build folder.
Probably easier to overwrite all during build with the latest chosen one.

**Comment by dairiki** [comment]
> I would say yes.
> On the other hand, I don't see a point in having different permissions on different files in this build folder.
> Probably easier to overwrite all during build with the latest chosen one.

Good points.  It may be best to behave differently in the two cases:
1. When creating output files (artifacts), always create with the default permissions (0o666 & ~umask).
2. When editing a file (e.g. `contents.lr`), preserve the existing file permissions. (That would mean preserving the file's group, too?)


Other issues:
- What if Posix ACLs are in use?  (If the containing directory has a default ACL set, that is used instead of the umask when creating a file.)
- How does this all translate when running on Windows?

**Comment by etoimene** [comment]
>     1. When creating output files (artifacts), always create with the default permissions (0o666 & ~umask).
> 
Instead of default, I would prefer what @narun4sk wrote earlier.
"ideally there should be umask setting within the Project File, so that users may choose whatever works best for them"

**Comment by dairiki** [comment]
It looks like I introduced this particular bug in [ba86d1c] (release 3.4.0b7).  Prior to that newly created artifacts were always given mode 0644 (regardless of umask).

[ba86d1c]: https://github.com/lektor/lektor/commit/ba86d1c6a64676583f711f566a1b4413f80ac892#diff-c1360c0fb130c5b6c80979a6ccc2a99bd9b95ad80af1e43af49eaebf43ccb922L722-L732

**Comment by etoimene** [comment]
It's always important to know who to blame. :) :) :) :) :) :)

**Comment by etoimene** [comment]
Also, not to complicate things 644 by default would probably work for 99,99% of people.

**Comment by dairiki** [comment]
> One solution may be:
> 
> 1. Read the current umask once at startup.  Maybe make this available from the Environment.
> 2. [Chmod](https://docs.python.org/3/library/os.html#os.chmod) files opened via `mkstemp` appropriately.

An alternative solution would be to essentially reimplement `tempfile.mkstemp`, modified to call `os.open` with `mode=0o666`  instead of with `mode=0o600` as `mkstemp` does. 
This has the advantage of letting the OS handle the application of umask or default ACL as appropriate.

FWIW, `tempfile.mkstemp` is not particularly complicated:  Here's the guts:

https://github.com/python/cpython/blob/dabcecfd6dadb9430733105ba36925b290343d31/Lib/tempfile.py#L243-L270
