### ISSUE TITLE
install shell script has some commands missing

### ISSUE THREAD

**Issue by SonakshiGrover** [lektor/lektor#193]
While running the project on Ubuntu , I encountered the following errors:

1) fatal error: Python.h: No such file or directory
     `#include <Python.h>`            

2) error: ffi.h: No such file or directory
    `#include <ffi.h>`

3) fatal error: openssl/e_os2.h: No such file or directory
     `#include <openssl/e_os2.h>` 

These errors can be removed by adding the following commands:

 sudo apt-get install python-dev
 sudo apt-get install -y libffi-dev
 sudo apt-get install libssl-dev

**Comment by mitsuhiko** [comment]
Hi. The install script does not install those. It's documented on the installation page, but not on the download page.

Maybe we could detect ubuntu/osx and then prompt for the right installation commands.

**Comment by SonakshiGrover** [comment]
Ohh ... I didn't read the installation page!

Yeah, we can add the following code snippet for detecting the OS:

import platform
if platform.system()=="Linux":
     print " Make sure that python-dev, libssl-dev and libffi-dev are installed" 
else :
    # continue

**Comment by vanadium23** [comment]
@nixjdm According to pip issue [#2933](https://github.com/pypa/pip/issues/2933), there is no way to add warning on `pip install` command. So where can we place this warning for end-user?

**Comment by nixjdm** [comment]
@vanadium23 I don't know of an easy / good solution for warning users who install with pip. Instead, we could check for the existence of those dependencies in the Python so that if they aren't there when people run lektor, it fails gracefully and tells them they need to install that dependency. Off hand I'm not sure where that logic should go. Sound good? I can change this issue's title to better fit that.

For those installing with the shell script though, we can place a note in that script letting people know they need those dependencies. That script is here https://github.com/lektor/lektor-website/blob/master/assets/install.sh (and thus changes to it would belong to that repository)

**Comment by yagebu** [comment]
I'm closing this issue since the install.sh script was completely replaced by a Python script some time ago.
