### ISSUE TITLE
JS error and admin freezes

### ISSUE THREAD

**Issue by tariquesani** [lektor/lektor#347]
I am using the latest master from the repo. When I try to load the admin I am getting "Uncaught TypeError: Super expression must either be null or a function, not object" in the console. The admin interface does not load after that.

![desktop screenshot](https://cloud.githubusercontent.com/assets/27067/22193583/660a5fea-e162-11e6-8aac-f193889d1ee8.png)

**Comment by singingwolfboy** [comment]
@tariquesani Thanks for reporting this! I can reproduce the problem, and I'm surprised that this bug got into master! Clearly, we need better automated testing...

I'm not yet sure how to debug this problem, since I can't figure out which line this problem is coming from. I'll keep poking at it in the next few days, and try to fix it. @mitsuhiko, if you want to help out with this, that would be greatly appreciated!

**Comment by tariquesani** [comment]
@singingwolfboy at this point I am happy that this is reproducible. I have had this issue previously as well but running npm update in the admin folder had solved it. There are others who have reported it before on gitter. AFAIK it is something to do with ES6 handling in latest React

**Comment by mitsuhiko** [comment]
This is most likely caused by mixing different import styles. They really should be converted to all ES6 imports.

**Comment by mitsuhiko** [comment]
I assume the root cause is the circular dependencies to the dialog system or widgets. This used to break before. Since the base component imports the dialog system when something along the chain changes there it can break and Component is undefined.

**Comment by pacahon** [comment]
I've tried other commits, it is broken for me with @4ddc3813cfa30401ab6c0dc6d6c23d1116ff9e7b, but ok with @bda45e36b33908831111e27746da01a34f335b36 (Looks like this error really related to imports)
After updating imports in `main.jsx` I got more detailed errors, but I'm not familiar with React/ES6 enough to continue investigation.
Also as I understood, `react-router` since 2.x has a battery for history, I have some sort of deprecation warning about that.

**Comment by tariquesani** [comment]
Yes. https://github.com/lektor/lektor/commit/bda45e36b33908831111e27746da01a34f335b36 is working fine for me thanks @pacahon I can live with that for a while :)

**Comment by coreygrunewald** [comment]
You can assign this issue to me. I work with React and JS daily.

**Comment by mitsuhiko** [comment]
@coreygrunewald that would be great!

**Comment by tariquesani** [comment]
@coreygrunewald would really appreciate a pull request. I tried changing the import statements but they kept leading me deeper and deeper into the rabbit hole

**Comment by coreygrunewald** [comment]
I'll be able to take a look this weekend.

**Comment by keikoro** [comment]
@coreygrunewald I pulled in your changes and while I still get some react warnings, it works for me – lets me finally access the admin interface, yay!

The only thing I can't do there is "Reveal in Finder" – `ReferenceError: makeRichPromise is not defined` – though I don't know if this is related or a whole different issue. (First time I'm using Lektor.)

**Comment by coreygrunewald** [comment]
@kerstin I refactored `makeRichPromise`, so this issue is due to me. I typically don't use the "Reveal in Finder" functionality, so I missed this in my manual regression. I'll fix this with another commit this weekend. Thanks for taking a look!

**Comment by tariquesani** [comment]
Seems to be fixed now. @singingwolfboy can we merge this into master?

**Comment by keikoro** [comment]
@tariquesani I think it'd be better to wait a few more days until the bug introduced with the fix is fixed also. (See comments right above yours.)

**Comment by tariquesani** [comment]
@kerstin it has been fixed. Thanks for the concern

**Comment by keikoro** [comment]
@tariquesani Oh, ok. I was looking at the PR but didn't see any updates to it, but maybe I looked in the wrong place.

Edit: Oh no, I did indeed *miss* it on the original PR. Sorry for the confusion!

**Comment by tariquesani** [comment]
https://github.com/lektor/lektor/pull/351/commits/07e417d0a5e4c5d471120e82ffe9ff0be50dbfb1 :)
