### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by coreygrunewald** [lektor/lektor#349]
Is there any documentation or thoughts around a release schedule for Lektor?

There have been quite a few changes since the last release in May of 2016. If assistance is needed for preparing a release, I'd be willing to contribute some time towards doing so.

**Comment by streaps** [comment]
It's time for a new release :) (IMHO)

**Comment by tariquesani** [comment]
Yes, it is time but currently the master is broken because of some ReactJS ES6 issues. Help is needed to solve that. See https://github.com/lektor/lektor/issues/347

**Comment by singingwolfboy** [comment]
@coreygrunewald: the blocking issue has been resolved, and I agree that we should prepare a new release for Lektor. Personally, I would definitely appreciate help with doing so. I'm particularly concerned about the documentation, and about the Mac app. I'll spend some time looking into this tomorrow, but I'm happy to hear any thoughts or suggestions about things we should do as part of the release process.

**Comment by coreygrunewald** [comment]
@singingwolfboy a few questions for context:

1. I don't use the Mac app - is it currently broken on `master`?
2. What features have been added / changed that would require updating the documentation?

In general, I would push for only doing what is necessary (e.g. documentation updates) in order to get this release out.

**Comment by streaps** [comment]
Any news regarding a new release?

**Comment by rixx** [comment]
FYI I'm building my new blog off `lektor`'s `master` branch and everything regarding to documentation works fine except for the [category](https://www.getlektor.com/docs/guides/categories/) guide which just resulted in no forms rendering at all.

**Comment by yuvadm** [comment]
Bump. Is Lektor development stalled?

**Comment by tariquesani** [comment]
Unfortunately, at the moment, yes.

**Comment by rixx** [comment]
Is there anything we can do to help?

**Comment by nixjdm** [comment]
To try to get this back rolling, it seems to me that the following can be done:

1. Work has been done since 2.3, and 2.4 and 3.0 deserve to actually be cut if they work. They are in the changelog. There isn't a tag though and they aren't available with pip. Master appears fine so hopefully we can find some commits to tag (maybe someone knows which ones?). By improving docs, we're talking about https://github.com/lektor/lektor-website, right? So that's not really a blocker depending on the feelings of those in charge here. We could just make issues for doc changes as we spot them, and patch them. getlektor already admits that it is "is a work in progress" anyway. Bumping to a new version here would go a long way towards the *impression* of progress and maybe get more people involved. Really, it would be acknowledgement of real progress.

1. There's some outstanding pull requests that anyone can take a whack at fixing. Some need a test, some need conflict resolution. Maybe that's some low hanging fruit for someone.

1. Correct me if I'm wrong, but there is no development or release guide anywhere, right? Even if it were something simple like https://github.com/mitchellh/vagrant/blob/master/RELEASE.md I'm betting that would remove some of the clouds about development here.

1. On top of that, better use of milestones would be awesome, and give devs something to focus on. Right now there's a milestone for 2.0 (way old) and 3.0 (already in the changelog). Those should be removed (esp. if 3.0 can actually be released) and some milestones for future versions should be made, and then some issues tagged.

Just my thoughts. I get that come of these things fall on the maintainers in control of this repo, and they are volunteers. I thank them for their work. Hopefully doing some of this will help the maintainers maintain with minimal effort too. I'd love to see Lektor really become popular.

**Comment by nixjdm** [comment]
FWIW setup.py never showed a version of 2.4, but 2.4 according to the changelog message should correspond to issue #228, and thus when commit 7fdbfff24712eb01c0ef31ab18d8c33342bba0cc was merged. 3.0 Was a commit made directly to the master branch and I don't think had a corresponding issue. 3.0 came with commit fda3a09ee5e8f66b062931bdf9feeec402f7deeb. Considering 2.4 didn't have the appropriate version number change in setup.py, I'd say just ignore it. Better yet, maybe even alter the changelog to put it's message inside 3.0's and get rid of 2.4 in the changelog to avoid future confusion. Can anyone with commit privileges tag 3.0? How about getting this on pypi? Anyone have experience with that?

**Comment by nixjdm** [comment]
There's been a number of commits and pulls since '3.0' (July 15, 2016). We could probably break this down in the changelog, make a few more tags, and push out some minor version changes too. Lektor development has slowed, but it's not as dead as it would appear.

**Comment by singingwolfboy** [comment]
I should have permission to publish to PyPI, and I'm happy to give that permission out to whoever wants to coordinate this new release. I'm also happy to provide advice, feedback, and support in this process, but I don't want to be the one responsible for making this happen. (I never really wanted maintainership of this project, I just [wanted to add Python 3 support](https://github.com/lektor/lektor/pull/207) and found myself suddenly in that position.)

**Comment by nixjdm** [comment]
Thanks for the response @singingwolfboy Well, I'm willing to do it :) I haven't published to pypi before, but I presume it's not that bad. Pointers are greatly appreciated.

**Comment by nixjdm** [comment]
So, fyi community, I now have the permissions to do some of the cleanup I mentioned above. I'll get started on all of that over the next few days. Soon we ought to be able to publish a 3.0.

**Comment by davidism** [comment]
Thanks for everything you've done for Lektor @singingwolfboy. Welcome to the team @nixjdm!

**Comment by nixjdm** [comment]
I am happy to announce new versions have been published to PyPI!

3.0 was released today, and a slew of quick bug fixes by @singingwolfboy to round out a nice 3.0.1. Master also contains these bugfixes, which also makes the Travis builds pass now. These commits are tagged with their version number.

There's still many more commits in master I'll try to weed through to make some future versions. That will take a little more time than just today, but I'll definitely look into it soon. I'll also make a release guide to make this a little easier in the future. I'm excited to be helping Lektor out. It's a good project and deserves some love.

Since 3.0 was released, I'm going to close this issue. :)

Thanks again @singingwolfboy!

**Comment by rixx** [comment]
Thank you very much for your efforts, @nixjdm!
