### ISSUE TITLE
Changing output paths for files and being able to use those URLs

### ISSUE THREAD

**Issue by timc3** [lektor/lektor#367]
Lektor at the moment seems to create a new slug with a index.html which is not shown when internal creating links. 

So the actual file might be `/example/index.html` but the link will show up as `/example/` which is fine for most web servers, but not really compatible with CloudFront subdirectories. Is there a way of exposing the ìndex.html` properly in the link or should we change the template file.

On related note to replace an existing site I might want to have it generate `/example.html` - is there a way of doing this?

**Comment by singingwolfboy** [comment]
It's entirely possible to set up Cloudfront to work with directory-based URLs. In fact, I have a tutorial for how to get Lektor set up with S3 and Cloudfront right here: https://www.davidbaumgold.com/tutorials/host-static-site-aws-s3-cloudfront/ The key is setting the "Index Document" option on your S3 bucket to "index.html", and making sure that you set up your Cloudfront distribution with the website endpoint URL from S3, rather than the default S3 URL that shows up in Cloudfront's drop-down menu.

Alternatively, if you want to generate URLs like `/example.html`, that's documented here: https://www.getlektor.com/docs/content/urls/#extensions-and-file-types

**Comment by timc3** [comment]
Thats good to know, I will try that out on our test environment. 

I am guessing the pertinent part is “If however the last path component contains a period (.) then the last path component is assumed to be a filename directly.”
