### ISSUE TITLE
Installation on shared server

### ISSUE THREAD

**Issue by wilfried18** [lektor/lektor#389]
How to install and test your cms on a shared server
thank you

**Comment by tariquesani** [comment]
Lektor generates, static websites which are deployed on the server. Lektor itself is not meant to be installed on the server.

**Comment by nixjdm** [comment]
The above is the straight forward answer, and I'd guess, probably what you're looking for. Scratching my head perhaps you wanted to install Lektor for development on a server, and have others access it, in which case perhaps the development instructions in the [README](https://github.com/lektor/lektor/blob/master/README.md) is more what you're looking for.

I'm going to close this since I think it's answered, but if you have further questions about how to use Lektor, please go to our gitter page and ask us some follow-ups. https://gitter.im/lektor/lektor
