### ISSUE TITLE
Make example project more full featured

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#435]
Currently the [example project](https://github.com/lektor/lektor/tree/master/example) and the project generated by the quickstart are identical (except for project name, author, and time created). Why have both of these if they're identical? Should their purposes be different?

My answer to those questions is that they should serve different purposes, and they should not be identical. If you have a good argument either way I'd like to hear it. I see quickstart as a great tool for beginning a project from scratch, and as such, it should be minimal, as it is, and only provide some basic code to get someone started. I see the example as just that, an example of what can be done. If that's the case, it can be better.

As an example, it should demonstrate Lektor's various features in a clear way. This example project would have a secondary utility of being a good project to develop against, especially if it uses more of Lektor's features out of the box. Of course the demonstration of all of these features should remain Spartan. The complexity of the example project will go up, but there needs to be a reason for that and it shouldn't be haphazard. The meaningful code should be easily identifiable. Ideally, most or all documented features would be used in one way. Off the top of my head, we can add

1. More sample blog posts so that there's some actual use of of pagination
1. Use of alternatives
1. Use of flow blocks
1. Use of expressions
1. Use of a databag
1. Use of attachments
1. etc., you get the idea

https://github.com/lektor/lektor-website Could use some updates as well, but I think the example project deserves to continue being separate. In the example project, we wouldn't see any long descriptions or explanations of what's going on, just usage examples. It should make for a great testbed for development.

**Comment by jvanasco** [comment]
a few comments:

1. it would be nice if there were ways to make other quickstart scaffolds/templates.  pyramid and some other projects offer this via the cookiecutter library (https://cookiecutter.readthedocs.io/en/latest/readme.html)

2. I just converted 3 "landing page" websites to lektor to simplify their management.  i'm unfamiliar with jinja2 and this integration, so had a few stumbling blocks.

* i integrated everything against the bootstrap css library.  i had some issues with getting the nav right, because the example I needed to see was:

    <li class="nav-item {% if this.path == '/' %} active"{% endif%}">

and not what we see in the examples:

	  <li class="nav-item {% if this.is_child_of('/about') %} active"{% endif%}">

* a modern template should take more advantage of metadata (and opengraph) tags.  extending the model to handle this was simple, but getting templates to chain-up via inheritance and still use fallbacks is a bit advanced.

* it would be nice to see how a simple macro is enabled and invoked. 

* it would be nice to have some tips/tricks for things like automatic navigation within a section.

* after playing around, I realized I could write a `_README.txt` file (or anything with a leading _ and it won't be copied into the project directory.  i'm not sure if that is intended or not, but I find it important to note in various builds a secret file like "this project is managed by ____, do not edit these files.  see /path/to for more info".  

* it would also make sense showing how to deploy an `.htaccess` file in the root.

**Comment by nixjdm** [comment]
I just started this work and put it in branch [example-project](https://github.com/lektor/lektor/tree/example-project). The first thing I tried to add was categories, prompted by a bug report with its use. That's a great example of why this is needed. That bug is #454.

**Comment by nixjdm** [comment]
The branch now has a better description of the project, tweaked README, more blog posts, blog navigation, pagination on the main blog page, and categories.

**Comment by goanpeca** [comment]
We should have all builtin types available as part of the models also

**Comment by nixjdm** [comment]
@jvanasco I like the Idea of having the quickstart becoming more full featured as well. I'll make a separate issue for that. *EDIT* On second thought, I think I want to flush this idea out a little bit more. It sounds awfully similar to [themes](https://github.com/lektor/lektor/issues/226). And that might be the better route, keeping the quickstart to only a few command options.

> I just converted 3 "landing page" websites to lektor to simplify their management. i'm unfamiliar with jinja2 and this integration, so had a few stumbling blocks.

Is your code by chance open source :) If it is we'd love to see it. If you want, you can even add it to the [Lektor Showcase](https://www.getlektor.com/showcase/) It sounds like you have a few examples of your own we could distill into this example project.

> example I needed to see was
... It looks like you didn't form your comment quite right here.

About the underscore thing, I think that's [an open bug report](https://github.com/lektor/lektor/issues/265)

**Comment by nixjdm** [comment]
@goanpeca I totally agree.

**Comment by jvanasco** [comment]
Sadly i'm not using lektor to manage any open source projects yet.  it's being used for some corp sites, etc.  

I copied my opengraph support to a gist.  It could be more dynamic for the `og:type` and should offer an og:image, but I didn't need that for my needs: https://gist.github.com/jvanasco/430dcfc485e1b729399023111b346603 (edited GIST)

eventually, I'll migrate a particular open source project onto lektor, and can share that repo via github once it's ready.

my thoughts around themes/quickstart are that a "familiar" approach works like this:

* lektor ships with multiple "templates"
* "quickstart" is the default "template"
* it would be nice a "template" included a bunch of functionality, so it effectively teaches you lektor

if you look at how pyramid uses cookiecutter (originally scaffolds) there are 3 official maintained "templates" that switched between the backing DB store (ZopeDB vs SqlAlchemy) and url routing method (traversal vs lookup).  

I'm putting "template" in quotes, because i'm really just talking about offering a scaffold with core functionality.  i'm not talking about visual themes, but enabling/disabling model types.  from what I looked at under-the-hood, lektor is doing a lot of this programmatically... however cookiecutter can automate it quite a bit.

**Comment by nixjdm** [comment]
I'll still work on this when I have the time, but if someone wants to contribute, please do! I have a [branch started](https://github.com/lektor/lektor/tree/example-project). If you work on this, submit a PR to that branch and I'll take incremental changes until its done enough to go into master. The last thing I was working on was adding examples of the various field types.

**Comment by davidism** [comment]
Since Open Graph was mentioned, I did release [lektor-open-graph](https://github.com/davidism/lektor-open-graph) for that, which is used on https://www.palletsprojects.com/, although it's in a very rough draft right now.
