### ISSUE TITLE
Remove the already deprecated build-flag option

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#525]
This flag was deprecated as of #326. It should actually be removed by the next major release. I'm making this issue to track that.

**Comment by animeshkrishnabulusu** [comment]
@yagebu I use `lektor -f minify` right now to minify static files. Can I just replace it with `lektor --extra-flag minify` once this takes effect?

**Comment by dairiki** [comment]
> I use `lektor -f minify` right now to minify static files. Can I just replace it with `lektor --extra-flag minify` once this takes effect?

@anmsh No, you are good as you are.  Since at least as far back as Lektor 3.1.0 (released in January 2018), "`-f`" is exactly equivalent to "`--extra-flag`".  (Except for the fact that its use will elicit a DeprecationWarning, `--build-flag` is also equivalent to `--extra-flag`.)

Thank you for the reminder, though!  I will work up a PR to fully remove `--build-flag` from Lektor 3.4.0.
