### ISSUE TITLE
don't upscale images during thumbnail creation

### ISSUE THREAD

**Issue by xlotlu** [lektor/lektor#540]
There should be an option to not create new images when the thumbnail would generate an upscaled version, but return the original image instance instead.

I propose an `upscale=False` kwarg to `image.thumbnail()`, and plan to default it to `True` at some point in the future.

**Comment by nixjdm** [comment]
@goanpeca what do you think? I'm all for adding an `upscale` kwarg, but my question is whether it should be default `False` or `True`. Current behavior would match default `True`. I don't really have any field data on this, but I'm guessing that's not a commonly used feature, especially intentionally. I know it's been this way, but I feel like it's worthy of calling a bug.

I'm leaning toward making it default to `False`, as per @xlotlu's proposal, and just trying to make sure we say it as loud as is appropriate in release notes since it is is kind of a breaking change (I say "kind of" because I'm inclined to view the original behavior as a bug, which would make this a bugfix).

I don't think anyone would be using the upscaling intentionally with good reason, right? This would have to be a case where they either can't get an image that's simply larger, or they don't care.

**Comment by goanpeca** [comment]
Hmmm, well I guess it depends, if the change will make images on existing sites become smaller, which could be a nuisance.

In general I think that it is expected behavior to return an (thumbnail) image of a given (specified) size, whatever that means (upscaling, downscaling). So I would be in favor of having the upscale `kwarg` but being by default `True` so that current behavior stays.

I don't think this is a bug and in that line I would propose to add a **warning** so that when the build process is happening we can warn users that some images have been upscaled and this might result in images of poor quality etc.

**Comment by xlotlu** [comment]
Or actually this would be a better idea:

```py
    def thumbnail(self, width=None, height=None,
                  crop=None, fit=None, scale=None,
                  quality=None):
        # ...

def make_thumbnail(...):
    if crop and fit or crop and scale or fit and scale:
        raise Exception("Specify at most one of `crop`, `fit` or `scale`.")
```

Allowing to specify `height` without `width` as above, and would default to `scale=True` unless `crop` or `fit`.

And in the future a breaking change could be to turn crop / fit / scale into `mode="crop / fit / scale"`, and default to... whatever seems right.

**Comment by nixjdm** [comment]
The format looks nice and tight which I like. I'm a little unclear on the meaning though. What's the difference between `fit` and `scale`? I'm guessing `scale=True` means upscaling still happens. I have a feeling that question would have an obvious answer to someone who knows how to use photoshop...

Having more granular control, or even additional ways of modifying thumbnails sounds great. Again, the way of structuring the mutually exclusive control vars looks good to me.

**Comment by xlotlu** [comment]
Well, when both width and height are specified, `scale` would mean to apply the distortion that's unwanted in (probably) 99% of cases. In contrast, `fit` would allow you to specify both dimensions, but have them behave like maximums instead, and scale the image proportionally until it fits that "frame".

Initially I thought `scale` mode should also always imply upscale, while `fit` mode shouldn't. Except I didn't fully think it through: for some strange reason, someone might always want to upscale, even in `fit` or `crop` mode. 

So now that I've been thinking about it, it looks like `scale`, `fit` and `crop` are mutually exclusive operations, while upscaling is orthogonal. The future API would then be

```py
    def thumbnail(self, width=None, height=None,
                  mode="fit", upscale=False,
                  quality=None):
        # ...
```

The problem with this design however is that when specifying only one of width or height, `fit` and `scale` mean exactly the same thing. Also, `crop` mode doesn't make any sense unless specifying both width and height.

I guess I could ~raise~ emit a warning if the mode is other than the default with a single dimension specified.

**Comment by xlotlu** [comment]
I intend to set up the clean, final API on `imagetools.make_thumbnail()` and emulate the current behaviour from `db.Image.thumbnail()`, along with warnings about bad arguments and future changes. `thumbnail()` should also get the new kwargs, so this will get us full backwards compatibility, pave the way for the breaking change, and allow people to start using it right away.

We just need to get that API right though, and something still bothers me about it. `scale` mode should imply `upscale=True`, while `fit` should imply `False`, but logical as it may be, it would make things confusing. Variable defaults = meh.

Actually. Step by step. First rename `scale` to `stretch`, this would make more sense. Then:
* fit mode:
  * thumbnail smaller than image: downsize to fit.
  * thumbnail larger than image:
    * upscale True: upsize to fit.
    * upscale False: return original.
* crop mode:
  * only makes sense with width and height specified. emit warning and fallback to fit mode otherwise.
  * thumbnail smaller than image: downsize and crop.
  * thumbnail larger than image:
    * upscale True: upsize and crop.
    * upscale False: «undefined behaviour». should one return the original untouched like in fit mode, or is this an error?
* stretch mode:
  * only makes sense with width and height specified. emit warning and fallback to fit mode otherwise.
  * thumbnail smaller than image: downstretch.
  * thumbnail larger than image:
    * upscale True: upstretch.
    * upscale False: «undefined behaviour». what now? I lean towards error.

**Comment by nixjdm** [comment]
With this renaming, `fit` will keep aspect ratio, correct? Since `stretch` seems intuitively like it will not, by the name.

`upscale=False` doesn't make a lot of sense in any situation, but now I'm rethinking this. I think I like the idea of returning the original in all three situations, and not raising an exception. The reason for that is I'm imagining someone using the same template code for many images, and they aren't carefully controlling the dimensions of the image, and they just don't want upscaling (because that's normal). Would it be better to upload 100 images and 7 raise exceptions because they're a little smaller than expected? That might be a painful situation. A warning is deserved I think, because the situation requested doesn't really make sense, but raising exceptions might be burdensome.

**Comment by xlotlu** [comment]
> With this renaming, fit will keep aspect ratio, correct? Since stretch seems intuitively like it will not, by the name.

Yes, that's the point, an alternative to the `maxwidth` / `maxheight` proposed initially. `stretch` is what nobody wants most of the time ~~, but is what happens now when giving both `width` & `height`~~ .

> upscale=False doesn't make a lot of sense in any situation, but now I'm rethinking this.

Did you mean `upscale=True`? `False` should be the future default, i.e. returning the original. (Rename this as well, maybe? I mean, I got it backwards as well, in the initial message even. "`force`" could be a good candidate, though it might create the impression that fit + force = forced stretch.)

> [...], but raising exceptions might be burdensome.

I was thinking of throwing / warning regardless of the size of the image, as I consider these more like "configuration errors" of sorts. The equivalent of a template error.

But regardless of throwing upscale-related errors being warranted or not  -- which I guess is not, we could even be totally quiet about our failing to come up with a mutually-exclusive logic :grin: --, I was thinking that a) warnings should be splurted out only once per run (I think that's how django handles deprecation warnings), and b) throwing an exception should break the build process entirely.

a) could be done easily (maybe I'll peek at how django does it) but b) isn't possible now, is it? IIRC (without testing) building tries the same template over and over again regardless of exceptions. If so, I think this should be a bug, and building be abandoned either entirely, or at least for the same template.

**Comment by nixjdm** [comment]
I mean that with `upscale=False`, you can't actually fit / crop / stretch, and simultaneously have a thumbnail that's actually larger than the image (as the dimensions would indicate). Thus, we return something reasonable but not what's literally being asked for; we return the original image.

I do want deprecation warnings.

I also am considering warnings for ever requesting `upscale=False` and the image being smaller than the thumbnail requested. Something like "Cannot fit / crop / stretch without upscaling since the image is smaller than the thumbnail requested. Returning original image." Maybe it's not needed if it's in the docs.

Right now when `lektor server` is run each artifact build failure / success is reported immediately and individually, and a final count of errors is reported after the whole site build is complete. I think I like this since it allows you to hack on one part of the site without bothering with a separate broken part of the site. Building a page is only attempted once until that file changes, exception or not. Lektor won't retry it blindly until it works if that's what you mean.

If an exception is encountered, `lektor build` will have an exit code of `1`, if success, `0`. This allows scripting.

**Comment by nixjdm** [comment]
> Building a page is only attempted once until that file changes

Well, actually, that's almost true, and the intention, but if a related file changes that also trips a rebuild. That's part of the scaling problems discussed in other issues.

**Comment by xlotlu** [comment]
> Thus, we return something reasonable but not what's literally being asked for; we return the original image.

That's where our views differ I guess. I started the issue because I find the current behaviour unreasonable (at least to my image gallery use-case, but i can't really imagine a scenario where someone would prefer an upscaled image), so returning the original should be expected behaviour. Maybe it's something that warrants logging at info level, but definitely not a warning. At least that's my take on it.

> I do want deprecation warnings.

Definitely. I was saying it would be nice to get the warnings only once, and not per artifact.

> I like this since it allows you to hack on one part of the site without bothering with a separate broken part of the site.

Yeah, that's nice. But ideally if a template error was encountered, nothing should be re-tried with that template until it changes. This is kinda both a bug fix and a performance fix.

**Comment by nixjdm** [comment]
:/ I think we agree, actually. Let me double check / try to clarify.

> so returning the original should be expected behaviour.

I think that is what I'm trying to say. It *should* be expected behavior, but currently isn't. So short term we pave the way to fix it, and long term we actually fix it (and break backwards compatibility). Short term, keep default `upscale=True` to keep backwards compatibility (which currently is implicit), but add the feature `upscale=False`. Long term, break backwards compatibility by making `upscale=False` the default.

Perhaps we disagree about what to do for `upscale=False`? I'm not sure. I was saying that should return the original image, which I think you're saying you want as well. The alternative is throwing an error.

Thanks for your patience hashing this out. It is a confusing topic.
