### ISSUE TITLE
Themes not working in Lektor 3.1.1

### ISSUE THREAD

**Issue by pjakobsen** [lektor/lektor#576]
`lektor --version 
Lektor, version 3.1.1`

Documentation implies Lektor now has theme support, but installing a new theme and setting it with the themes variable in .lektorproject results in the following:

Some of the files from the new theme get included in the new build.   
But, the css file from the default quickstart project seems to stick around
In the end it looks like the themes support is simply broken and that it fails silently. 

The documentation should either be updated to reflect this reality, or the themes feature should be completed.  

I tried to read the source code to see if I could fix it, but it's way too complicated!

**Comment by nixjdm** [comment]
This sounds like you have conflicting files in your project as you do in your theme. When that happens your existing project files are used instead of the theme's files. This is on purpose to allow the themes to be flexibly overridden.

Can you check this? Compare `ls themes/[theme-name]/templates/` to `ls templates/`, for instance. Models would work the same way.

I do have a site using themes that works with 3.1.1 / master. I'm betting this what's going on.

**Comment by pjakobsen** [comment]
Thank you @nixjdm -   Can you give me an example of one conflicting file?   Do you mean, for example, styles.css should only exist in one of the templates directories?  Thanks :)

**Comment by pjakobsen** [comment]
This may seem like splitting hairs, but it does seem the themes document need to be a bit more precise; For example, from https://www.getlektor.com/docs/themes/installing/

> For installing a theme you just need to copy it to the themes/ folder

But after running quickstart to create a new project there is no themes folder in that projects folder.  So perhaps what the documentation wants to say is something like 

> After creating a new project with Quickstart, add a 'themes' folder to the root project folder.

**Comment by nixjdm** [comment]
> Do you mean, for example, styles.css should only exist in one of the templates directories?

Yes. This is why, for instance, the terminal theme produces a stylesheet of a different name https://github.com/terminal-labs/lektor-theme-terminal/tree/master/assets/static/css That way a project specific style.css can still be used without overwriting the theme's styles.

From the docs:
> This allows you to use assets, templates, models, and / or flowblocks built into the theme

Any of those file types can be used by a theme, and optionally overwritin by a project's files. I can change the docs to try to make that more clear.

I'll also change  the docs to clearly state that you need to create `themes/` if it doesn't exist (such as with the quickstart).

**Comment by nixjdm** [comment]
https://github.com/lektor/lektor-website/pull/234

**Comment by pjakobsen** [comment]
As a complete newbie, I had falsely assumed the basic lektor workflow was:

1. install lektor 
2. Run quickstart to create a site
3. Install a new theme as documented  in  https://www.getlektor.com/docs/themes/installing/

If there is a missing step in this workflow, like removing the default theme that quickstart created, that should probably be documented. I'd like to assist with that, but I'm still not clear on what the missing step is.  I will experiment some more to see if I can get the new theme working.  Thank you for you help. :)

**Comment by nixjdm** [comment]
I agree that the documentation should be made more clear. Theming does work though, so since this is mainly a documentation issue I'm opening https://github.com/lektor/lektor-website/issues/240 and closing this issue.

Briefly, that workflow is not the end of the story. After your step 3 you'd need to modify your project to actually use the installed theme, and how precisely to do that depends on the theme (and your existing project, but in your example's case it's simply the quickstart).

> like removing the default theme that quickstart created

At this time the quickstart does not use a theme. It is a normal, theme-less Lektor project. #535 would change that and hopefully make adopting a theme from the quikstart state a little easier. For now though, the expectation is that there are manual steps to use a newly installed theme after it's installation.
