### ISSUE TITLE
AsciiDoc

### ISSUE THREAD

**Issue by nancym** [lektor/lektor#6]
I see that Lektor supports Markdown and I'm wondering if it supports AsciiDoc too. It would be great if it does. AsciiDoc >> Markdown  :smile:

**Comment by mitsuhiko** [comment]
Yes, but not built in.  I want to make it possible to plugins to provide their own types.  The reason I do not want it built-in is because that will feature creep quickly.  Markdown is kinda accepted at this point as a standard and the idea would be to have a GUI for it that hides Markdown.  See #7.

**Comment by mitsuhiko** [comment]
Lektor 2 makes it possible to implement custom types at least on a basic level.

**Comment by gotwf** [comment]
Apologies for the necro comment but I beg to differ with Markdown having become accepted standard.  Indeed, with so many extensions/flavors, it's anything but.  OTOH, asciidoc just gets the job done.  Simplicity when you want it and more power when you need it.  O'Reilly now uses asciidoc.  That is a LOT of publishing.  

The edge markdown has is for those _already_ familiar with it, usually devs via github.  Regular users w/o a dog in the fight?  I'd used markdow some.  Pretended I hadn't and gave asciidoc a try.  So much nicer.  

So mayhaps reconsider this: ship with both markdown and asciidoc and you've covered the lions share of all use cases.  

Your admin in a nice touch but I'll still use emacs to compose content.

Peace---
