### ISSUE TITLE
Lektor backend: when using double dot (colon) in ID, interface screws up

### ISSUE THREAD

**Issue by torian257x** [lektor/lektor#610]
you click add page

you enter as id

`Sometext adasdf: asdfasdf asdf asdf asdf`

the result will confuse lektor, as the `:` is used in lektor backend navigation / routing 

`:` is not treated as illegal, but should be and replaced

**Comment by tgpfeiffer** [comment]
I have created a fix for this where the colon would generally be disallowed as a character in the ID: https://github.com/lektor/lektor/compare/master...tgpfeiffer:610-disallow-colon

However, I am unsure if this is too strict, i.e., if maybe just the admin interface should replace the colon by a hyphen before submission, because it is actually only related to the admin interface. (One could argue, though, that a colon in the ID leads to a colon in the directory name, which is not possible on Windows; so for OS compatibility it should be generally forbidden.) Any opinions? Should I send a PR?

**Comment by dairiki** [comment]
I think plus signs (`+`) in page ids will cause trouble as well, as that conflicts with the way alts are currently encoded into the admin URLs.

So, one fix would be to forbid both `:` and `+` in page ids.  As you note, @tgpfeiffer, Windows doesn't allow `:` in filenames, so that's not a bad restriction. Plus signs are allowable in file names, however (though their use may cause confusion with the way Lektor uses them in filenames.)

An alternative way to fix this issue would be to rejigger the way the Lektor path gets encoded into the admin GUI URL.
E.g. change the React [route pattern][] from `${root}/:path/:page` to `${root}/:path*/:page` (the [asterisk][] means that the `:path` part may contain zero or more /-separated components), and pass the alt as a query arg, so that the edit URL, instead of being something like `/admin/root:blog:first-post+de/edit` would be the (cleaner, I think) `/admin/blog/first-post/edit?alt=de`.
(This might also be a way to fix #975.)


[route pattern]: https://github.com/lektor/lektor/blob/2e06c93aec8e4bdab6f35862ca6e2a73a2eb4b46/lektor/admin/static/js/main.tsx#L44
[asterisk]: https://github.com/pillarjs/path-to-regexp/tree/v1.7.0#asterisk
