### ISSUE TITLE
Is there any way to stop dev server from inside a plugin?

### ISSUE THREAD

**Issue by germn** [lektor/lektor#631]
I write plugin and let's say `on_before_build_all` I faced a problem that makes impossible to build things futher. Is there any way to stop dev server then?

Throwing exception doesn't work (`lektor` tries to re-run things) and `sys.exit(3)` doesn't seem to stop some background process.

**Comment by runfalk** [comment]
This is because `lektor server` will spawn a separate process for the development server. Lektor uses [werkzeug](https://github.com/pallets/werkzeug)'s `run_simple`. If the dev server crashes or exits it will simply restart.

Could you elaborate why it is not possible to build things without restarting? If this is a valid use case, maybe we should look into a solution for it.

**Comment by germn** [comment]
@runfalk I write my own webpack support plugin. If user, for example, doesn't have nodejs installed at all it doesn't make sense to continue with lektor either. I think most expected behavior is to print error and shutdown lektor.

**Comment by germn** [comment]
ok, I dig source code and it seems to be impossible. As a (dirty) workaround I'm killing current process and all it's children:

```
import os
import psutil


def kill_process_and_children(pid):
    process = psutil.Process(pid)
    for proc in process.children(recursive=True):
        proc.kill()
    process.kill()

pid = os.getpid()
kill_process_and_children(pid) 
```

**Comment by nixjdm** [comment]
@germn FWIW, I'd just add a hook to different plugin event if you want to check for node being installed, prior to the dev server being spawned, like `setup-env`.

**Comment by germn** [comment]
In case someone will search it, correct solution is obviously just manually raise `KeyboardInterrupt`. It'll gracefully shutdown dev server.
