### ISSUE TITLE
Example doc for databags uses `.iteritems` method, not in Python 3.6.6

### ISSUE THREAD

**Issue by barryrowlingson** [lektor/lektor#643]
In the docs for databags:

https://www.getlektor.com/docs/content/databags/

the code uses `.iteritems` to loop over items in the data bag. This method isn't present on an OrderedDict in my Python 3.6.6, so an error results when lektor tries to render the page. My `OrderedDict` has these methods:

```
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> d = collections.OrderedDict()
>>> dir(d)
['__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'move_to_end', 'pop', 'popitem', 'setdefault', 'update', 'values']

```

and replacing with `.items()` seems to fix it.

I can't find where in the python changelogs this happened...

**Comment by runfalk** [comment]
This is because `iteritems` was never added to `OrderedDict` in Python 3. `OrderedDict` was released for Python 3.1 and then backported to Python 2.7. `iteritems` is specific to Python 2.7 and is _almost_ equivalent to `items` in Python 3.

Python 2 is becoming more obsolete by the day, so I think it makes sense to make the documentation be Python 3 favoured. In this case we can use `items` since it works on both Python 2 and 3, though less performant on Python 2.

Thoughts @nixjdm?

**Comment by davidism** [comment]
For these sorts of uses, I usually just switch to `items`. There's unlikely to be a large enough collection to really matter, and the performance hit is probably negligible in context.

**Comment by goanpeca** [comment]
>Python 2 is becoming more obsolete by the day, so I think it makes sense to make the documentation be Python 3 favoured. In this case we can use items since it works on both Python 2 and 3, though less performant on Python 2

👍
