### ISSUE TITLE
Date picker overflows admin page width

### ISSUE THREAD

**Issue by davidferguson** [lektor/lektor#648]
It seems that the date picker widget in it's current form always occupies a set minimum width. Therefore, it can overflow the admin page body in some cases, as shown in the image blow:

![date-overflow](https://user-images.githubusercontent.com/13520342/57143444-d0703200-6db6-11e9-98aa-77e99e239efc.png)
(image taken from the the blog page template from the example project)

I was only able to "fix" this by decreasing the font size of the date picker, which is not an ideal fix.

This is for screen widths between 1024px and 1365px.

**Comment by nixjdm** [comment]
This is much more apparent on Chrome than Firefox, but it still is a problem. I didn't notice that when I added made this example project page. In both browsers, it looks like it ought to be able to be made to fit by reducing the space around the date string in the field.
![publicationdate](https://user-images.githubusercontent.com/3431410/59629644-edfc1f80-9108-11e9-8585-67afb59ee875.png)

Another way we could solve this is by prohibiting the `date` field type from really using a width as small as 1/4. The way [it's written right now](https://github.com/lektor/lektor/blob/master/lektor/admin/static/js/widgets.jsx#L106-L110), the widths are rounded to bootstrap columns from 2/12 to 12/12. Since we don't allow the 1/12 width, we don't run into this problem with other fields. At greater than 1/12 widths, I'm pretty sure the only problem field type is `date` because it has a fancy embedded widget. If we amend the jsx logic to force `date` widgets to be >= 1/3 (4/12, or `col-md-4`), then we'd avoid this and let the widget look it's natural way.

If someone chose a smaller width, we'd silently correct to 1/3. We already correct to something simple without telling anyone in other situations, like when we get widths like 1/9, so we can do that here too, just in a slightly special way. It may be a little unexpected, but will at least look good. When done, there should be a quick mention on https://www.getlektor.com/docs/models/#fields and https://www.getlektor.com/docs/api/db/types/date/
