### ISSUE TITLE
Builds on master seem to have issues

### ISSUE THREAD

**Issue by goanpeca** [lektor/lektor#652]
We are using master to deploy our site with Travis CI and the following error appeared:

```python-traceback
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/lektor/pluginsystem.py", line 164, in emit
    rv[plugin.id] = handler(**kwargs)
TypeError: on_setup_env() got an unexpected keyword argument 'extra_flags'
```

**Comment by nixjdm** [comment]
The plugin you're using doesn't accept `**kwargs`. It needs at least `def on_setup_env(self, **extra):`, since master is now passing `extra_flags` to all plugin events. If this is a public plugin that's having the trouble, we should let them know. Otherwise you need a quick commit to your custom plugin. :)

This is old advice on https://www.getlektor.com/docs/api/plugins/events/#handling-events, so I didn't consider it a breaking change when merging #651.

----

That said, does the full traceback indicate which plugin it is? We could improve it to be more informative if not. If it's not a custom plugin, the cache dir is outputted with `lektor plugins reinstall`, which would help a grep.

**Comment by DeeUnderscore** [comment]
My tracebacks for an analogous issue with lektor-shortcodes did not mention the specific plugin. Thanks for the grepping tip, though.

**Comment by nixjdm** [comment]
I'm glad you found it. Thanks for the feedback. I'll make another ticket to make debugging this particular error a little easier.
