### ISSUE TITLE
__pycache__ warning when multiple plugins are used

### ISSUE THREAD

**Issue by maxbachmann** [lektor/lektor#659]
when installing multiple plugins there is always the warning:
```bash
WARNING: Target directory /home/travis/.cache/lektor/packages/ec9db1d8e19c815059a5bf96f267136f/__pycache__ already exists. Specify --upgrade to force replacement.
```
is this a problem? What does this warning even indicate?

**Comment by nixjdm** [comment]
This is generally not a problem. That `.cache/.../__pycache__` dir contains pyc files of the plugins you have installed. When you add a new plugin, that `__pycache__` will be added to when the new plugin's code is byte-compiled. If all you're doing is adding or removing plugins, then you should be fine. pip checks for the existence of this dir and sends out the warning because it (and we) can't know for sure if everything is ok. It's a possible indicator of an dependency (plugin) installation problem. In practice, with normal lektor use, everything's fine.

If you *are* having problems, run `lektor plugin flush-cache` to entirely wipe clean the `.cache` dir and force it to start from scratch. It is possible to corrupt your cache, but generally only if you're doing plugin or lektor development, or otherwise playing loosely with virtual environments/pip/etc in unsupported ways.

**Comment by maxbachmann** [comment]
thanks for the clarification. I did not have any problems with it, but I wanted to be sure it´s no problem, because someone in my team told me my plugins are broken and so we can´t use them based on this warning. I already kind of expected there is no real problem because it´s just a warning and everything worked completely fine ;)

**Comment by nixjdm** [comment]
Right, it's a warning because it *could* be a problem, but it almost certainly isn't in this case. It's also emitted by pip directly, and they (and we) don't know what happened necessarily outside of that command, so they're just being cautious. Maybe "caution" would be better than warning, but it's outside of Lektor's scope to control. Hope that helps!
