### ISSUE TITLE
Deprecation warning for watchdog

### ISSUE THREAD

**Issue by thmsklngr** [lektor/lektor#687]
Hi,

just started using Lektor (awesome!) and saw this deprecation warning for watchdog:

`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

I also reported this to the author @gorakhargosh but it seems that he does not picks up issues from Github (lots of unreplied issues).

Regards from Lower Austria, Thomas

**Comment by skorokithakis** [comment]
Hello, thanks for the report! Unfortunately this looks like something that needs to be fixed upstream, as I don't think there's an elegant way to fix it downstream...

**Comment by nixjdm** [comment]
Actually it looks like this is already fixed in watchdog's master branch as of a few months ago with https://github.com/gorakhargosh/watchdog/pull/575. It just needs to make it into a new release of watchdog now. I imagine that won't happen too long after 3.8 is ready, but I'll keep an eye on it.

Thank you for the report! Since this is fixed over there, I'm closing this.
