### ISSUE TITLE
Allow process_image to accept extra parameters to ImageMagick

### ISSUE THREAD

**Issue by skorokithakis** [lektor/lektor#691]
I have found that I can halve my image size if I pass `-strip` to ImageMagick. Due to my thumbnail plugin being what it is, I would greatly benefit by `process_image` being able to accept a list of extra parameters to pass to ImageMagick.

It would not be appropriate to include these parameters in `process_image` in mainline because not everybody wants thumbnail-quality, but for my plugin they're ideal. Would this be a desirable PR to open? If so, I can submit it ASAP.

What do you think, @nixjdm?

**Comment by goanpeca** [comment]
Hi @skorokithakis, could you post a small snippet of how this would look like to a user?

Would it just accept any other parameters? or would it be a `kwargs**` kind of thing or :-) ?

**Comment by skorokithakis** [comment]
Certainly!

The signature would change from:

```python
def process_image(ctx, source_image, dst_filename,
                  width=None, height=None, mode=ThumbnailMode.DEFAULT,
                  quality=None):
```

to:

```python
def process_image(ctx, source_image, dst_filename,
                  width=None, height=None, mode=ThumbnailMode.DEFAULT,
                  quality=None, extra_params=None):
```

And the invocation would become:

```python
process_image(ctx, "in.jpg", "out.jpg", 100, 100, extra_params=["-strip"])
```

**Comment by goanpeca** [comment]
@skorokithakis yes I think I have seen this. How about extra params with values?

```python
process_image(ctx, "in.jpg", "out.jpg", 100, 100, extra_params=["-some-param value"])
```

?

Could/Should it be a dictionary? I think I have also seen this like:

```python
process_image(ctx, "in.jpg", "out.jpg", 100, 100, extra_params={'strip': '', 'otherparam': 'value'})
```

Which would allow for some easier validation, I do not expect those extra params to varied that wildy or too ofter, right?

**Comment by skorokithakis** [comment]
I would prefer to keep them as a standard popen-compatible list so the code can then just be `cmdline += extra_params`. It's a very standard and well-known interface.

Values would be passed in the list, e.g. `["-interlace", "Plane"]`, as usual.

**Comment by goanpeca** [comment]
> would prefer to keep them as a standard popen-compatible list so the code can then just be cmdline += extra_params. It's a very standard and well-known interface.

Right! 

Yes in that case I am :+1: on this :-)

**Comment by skorokithakis** [comment]
Great, I will submit the PR soon.

**Comment by skorokithakis** [comment]
Damnit, I pushed to the wrong origin by mistake :(

**Comment by skorokithakis** [comment]
Sorry about this, I force-pushed just now to revert the commit, hopefully I didn't overwrite anyone's push.

**Comment by skorokithakis** [comment]
This conflicts with pluggable backends and will not be implemented.

**Comment by xlotlu** [comment]
Guys, sorry for being undecided, but I'd like to revisit this. What convinced me was taking a look at lektor-thumbnail-generator's [code](https://github.com/skorokithakis/lektor-thumbnail-generator/blob/c672de4febfd51e3daac6fd1cd4976145900c1c7/lektor_thumbnail_generator.py#L17), and seeing that due to my stubbornness a while ago (https://github.com/lektor/lektor/pull/692#issuecomment-537954928), it's basically just a copy-paste of the core code that misses on fixes. This is a bad stance towards our plugin developers.

The rationale for re-opening this is twofold:

a) given that pluggable backends didn't happen yet,
b) and more importantly, even with pluggable backends we'd probably have to support bakend-specific options, so why not accommodate it already and change the code as deemed necessary in the future (along with the plugin-usable API).

@goanpeca / @runfalk / @nixjdm what say you?

One thing I'd implement differently from #692 though is using `**params` instead of `extra_params=None`, so we leave the door open to override more of the existing kwargs. One scenario I have in mind is overriding the thumbnail quality, and we should probably make `strip=True, colorspace="sRGB"` kwargs too.

**Comment by skorokithakis** [comment]
I'm obviously in favor of this as well. However, wouldn't using `**params`(/`**kwargs`) mean that we wouldn't be able to add single options, e.g.`-strip`, since we wouldn't be able to differentiate between `-strip` and `-strip=True`?

I think the parameters passed to Imagemagick should be in their own, well-defined variable, rather than hijack the top-level namespace and become commingled with the parameters to the actual function.

**Comment by xlotlu** [comment]
> I think the parameters passed to Imagemagick should be in their own, well-defined variable, rather than hijack the top-level namespace and become commingled with the parameters to the actual function.

The way I see things, treating the final executable as something separate from the function itself is a strategic mistake. It's also the reason why I objected initially, because it ties us to something way, way too specific - the imagemagick cli.

We should think in terms of Python API, not in terms of the backend's technical specificities. I don't see this as hijacking, but as crafting a well-thought interface, from the user-facing config to the plugin-usable function signature.

> However, wouldn't using `**params`(/`**kwargs`) mean that we wouldn't be able to add single options, e.g.`-strip`, since we wouldn't be able to differentiate between `-strip` and `-strip=True`?

Say "`strip`" is a config item. It could be something that all backends must support, or something specific to only one. In either case, the config line should look like `strip = yes`, and the same goes for the function signature. What happens if a backend receives an unknown param, that remains to be seen.

I hope I'm not mistaken, I think in the case of imagemagick's cli things consistently translate such that:
- `func(param=True)` results in `cmd -param`,
- `func(param=False)` results in `cmd +param`,
- `func(param="string")` results in `cmd -param string`.

If we do the right thing here, we should end up with something that, when the time comes, is readily transformed into the "imagemagick-cli image processing backend".

**Comment by skorokithakis** [comment]
In that case, yes, but then there has to be an abstraction layer that supports some set of functionality common to all backends, or with ways to specify which functionality each backend supports.

It might also be more useful to define things in non-imagemagick terms, if only to avoid making it too specific conceptually (because then other backends would basically have to emulate the imagemagick cli parser).

**Comment by runfalk** [comment]
This is a tough one. Maybe we could export the configurable API under a new name that clearly indicates that it's backed by imagemagick? So you'd do something like:

```
this.image|imagemagick_thumbnail(480, 360, strip=True)
```

That way we have the opportunity of switching backends in the future and move the imagemagick backend to a plugin in a fairly backwards compatible way.

**Comment by xlotlu** [comment]
> In that case, yes, but then there has to be an abstraction layer that supports some set of functionality common to all backends, or with ways to specify which functionality each backend supports.

@skorokithakis yes, the cleanest way would probably be to use classes. I started working on a prototype back when I created #609, Maybe I'll give it another try next week.

> It might also be more useful to define things in non-imagemagick terms, if only to avoid making it too specific conceptually (because then other backends would basically have to emulate the imagemagick cli parser).

Right, the Python API should come first, and how it reflects for the users in the config. (and its usability for plugin writers.) But I suggest we start small by simply changing the current function's signature to a) make sense pythonically, and b) be useful to you (afaik there aren't any other image-related plugins out there).

>  So you'd do something like:
> 
> ```
> this.image|imagemagick_thumbnail(480, 360, strip=True)
> ```

@runfalk  I think that would complicate things unnecessarily. The template shouldn't care about which backend is in use, except of course when using a backend-specific option. But in all other cases, when one would want to switch, say, from imagemagick-cli to libvips for speed improvements, it should be nothing more than a conf change. I'm thinking the default would be something like

```ini
thumbnail_backend = "lektor.imagetools.backends.ImagemagickCLI"
```

**Comment by runfalk** [comment]
So, I don't necessarily think we should have pluggable backends to be honest. As I see it it'll only increase complexity for little to no benefit. If we find something we like more than imagemagick we'd just replace it completely. Is there a valid use case here?

It seems I didn't make myself clear enough. I think the current `|thumbnail()` should stay as it is. What I meant is that all imagemagick specific options we expose should be done though a separate filter like I described. If we ever want to yank imagemagick from core we can provide a plugin that polyfills that functionality so people don't have to change their content.

**Comment by xlotlu** [comment]
>So, I don't necessarily think we should have pluggable backends to be
>honest. As I see it it'll only increase complexity for little to no
>benefit. If we find something we like more than imagemagick we'd just
>replace it completely. Is there a valid use case here?

That does make sense, but unfortunately the rationale is more of a logistical nature: vips is pretty finicky to install on windows. Different features are just icing on the cake.

If you have a photo-heavy site you do want a vips beckend, if you're savvy enough to make it work. Of course, had we had an installer bundling dependencies, this would be moot.

I do think though that this "increased complexity" forces us to come up with a clean API, which is a good thing. Yes, we could improve things without pluggable backends, but hey, who'd take up this task?

>It seems I didn't make myself clear enough. I think the current
>`|thumbnail()` should stay as it is. What I meant is that all
>imagemagick specific options we expose should be done though a separate
>filter like I described. If we ever want to yank imagemagick from core
>we can provide a plugin that polyfills that functionality so people
>don't have to change their content.

Ok, but I still find it ugly.

**Comment by runfalk** [comment]
If you're doing photo heavy work and want to invest time in making a vips thumbnailer doesn't it make more sense to just vips support as a plugin? I assume you can just override the `|thumbnail()` filter in the jinja env setup hook. Even if you can't override it you can just register an alternative filter `|thumbnailify()` or something.

It might make sense do the plugable backends if we officially support multiple backends I guess. Though I'm not too keen on that idea from a maintenance/testing point of view. If libvips is better than imagemagick in most aspects but windows installation process, doesn't it make more sense to solve that bit and just go vips?

To be clear. I won't stop someone from merging pluggable backend support (and I'll happily review such a PR), but I'm not convinced it's a good idea.

> Ok, but I still find it ugly.

Fair enough :smile:

**Comment by xlotlu** [comment]
@runfalk it would be nice to copy / paste some of your points under #609, where the discussion makes more sense.

Re: `thumbnail()`, it is an Image method, but I guess that doesn't really matter, a plugin could do the job, and it may be a good idea for the code to start that way, as a proof of concept.

In this context though, the point was creating a clean interface for the current `process_image`, such that it's useful to all users. I know I caused it, but I think pluggable backends are a red herring in this case, we should just focus on that function's signature.

My proposal was:

1. To move things that are hardcoded within that function into kwargs. For example, strip=True and colorspace="sRGB" make sense *as defaults* for a web publishing platform when thumbnailing, but they should be changeable (if nothing else, for https://github.com/lektor/lektor/issues/607). If we change the backend in the future it's moot, that backend should support colorspace changing and stripping, because they're essential to file size.

2. Allow for open **kwargs. @skorokithakis for example likes to blur his thumbnails (https://github.com/skorokithakis/lektor-thumbnail-generator/pull/3#issuecomment-678832714). I definitely wouldn't want to support "blur" as an official param though, nor any other imagemagick-specific stuff. If it should be done via `**kwargs` or via `extra_params=None` is a point of finesse and an opportunity for much bikeshedding. We should consider though, that `process_image` is, in the end, a pretty low-level thing: lektor core itself jumps through a few hoops until it gets to call it. If at some later point we want to expose this to our users, it may make more sense to set something like "IMAGEMAGICK_PARAMS" in config instead of passing things through from the template.
