### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by ghost** [lektor/lektor#718]
I am not seeing any support for tags. Is that the case?

https://gohugo.io/content-management/taxonomies

**Comment by runfalk** [comment]
You can have something like tags. It is described here: https://www.getlektor.com/docs/guides/categories/

**Comment by ghost** [comment]
How would you add catgories to an individual page? Can pages have more than one category?

**Comment by runfalk** [comment]
> How would you add catgories to an individual page?

In the example you use checkboxes, but it can be implemented any way you want. Lektor is very flexible when it comes to how you want the admin to work.

> Can pages have more than one category?

For the example, yes they can.

**Comment by ghost** [comment]
@runfalk sorry but I have no idea what you are talking about. Can you point to an example repo that has tagged pages? I see this:

https://github.com/lektor/lektor-website/tree/master/content/blog

but none of the pages have tags

**Comment by runfalk** [comment]
I meant the example as the guide I sent. I don't know any repositories that does this.

**Comment by xlotlu** [comment]
> I am not seeing any support for tags. Is that the case?

That's because there is no "support" for anything. Lektor does not work like other static website generators; it is [datamodel-oriented](https://www.getlektor.com/docs/models/), which means you define your own fields, as opposed to with preset given fields.

Do read the documentation and look at [the guides](https://www.getlektor.com/docs/guides/) for inspiration. Also, direct support questions to the [gitter channel](https://gitter.im/lektor/lektor).
