### ISSUE TITLE
[CI] tests order

### ISSUE THREAD

**Issue by xlotlu** [lektor/lektor#780]
I would like to see the Windows 3.8 tests run right after the Linux 3.8. Also, any other tests on the same platform should be gated by py-latest.

So (as far as python tests are concerned, I have no opinion on the js stuff), I think it should work like this:

- 3.latest Linux  - gates everything
- 3.latest Windows - gates everything windows
- 3.latest MacOS  - gates everything mac
- 2.7 Linux, Windows, Mac
- 3.* Linux, Windows, Mac 

The big changes would be rethinking gating and reordering tests by python version, as opposed to platform.

**Comment by runfalk** [comment]
I guess we could technically list all os/pyversion combinations manually instead of automatically calculating the build matrix. That way I guess order is ensured.

It already cancels the entire matrix (or is supposed to) when the first one fails. If we gate too many things we don't get the benefit of parallelism. Since there are platform specific steps I think it may be complicated to group by version instead of OS, but I could be wrong.

Could you elaborate why you think it's important to do it this way?

(We should probably wait for #748 before any work is done on this as well)

**Comment by xlotlu** [comment]
> Could you elaborate why you think it's important to do it this way?

I had a windows-specific bug the other day. Windows tests run last (3.8 happens to be the final one), and they all failed.

> It already cancels the entire matrix (or is supposed to) when the first one fails. If we gate too many things we don't get the benefit of parallelism. 
> I guess we could technically list all os/pyversion combinations manually instead of automatically calculating the build matrix. That way I guess order is ensured.

I'm not *all* that set on the ordering above. Just latest python on all platforms would be nice, as gate-keeper.

> (We should probably wait for #748 before any work is done on this as well)

@goanpeca probably has a clearer view of what it would take.

**Comment by yagebu** [comment]
To speed up the test runs, the gating of tests has mostly been removed now, so I think this issue doesn't really apply anymore.
