### ISSUE TITLE
Switch to slugify breaks slugs using .html

### ISSUE THREAD

**Issue by funnelfiasco** [lektor/lektor#795]
I'm in the process of moving my website from Blatter, which has been dead upstream for years, to Lektor. I wanted to minimize the changes to existing page names in order to not break inbound links (or make a big list of http redirects), so I've been using the `_slug` attribute in `contents.lr` to do that. For example: `_slug: airports.html` in *content/ben/airports/contents.lr* so that the resulting rendered page is */ben/airports.html*.

For some pages, I have capital letters (because they're acronyms), but the slug always ended up lowercase using the latest release. So I switched to the latest Git snapshot, and now the `.html` gets treated differently. `_slug: AFDAFC-201208270030.html` in *content/weather/fd-hof/AFDAFC-201208270030/contents.lr* results in a rendered page *weather/fd-hof/afdafc201208270030-html/index.html*. The "airports" example above becomes *ben/airports-html/index.html*.

Is there any way that I can get the behavior I was getting from the released version (but with with more literal interpretation) or should I change my approach (by switching tools or just abandoning my previous layout and using HTTP redirects)?

**Comment by runfalk** [comment]
This does sound like a bug to me. According to the docs you are supposed to be able to do this.

https://www.getlektor.com/docs/guides/error-pages/

**Comment by dairiki** [comment]
I hadn't looked into it closely yet, but I think this is probably related:

Recently, while working on a site, I upload an image attachment to a page.  Using the UI to upload an attachment with a name like `image.jpg` resulted in the attachment being named `image-jpg` (rather than the expected `image.jpg`.)  This is bad, since it breaks mime-typing via file extension.  As I was in a rush. I worked around this by manually copying the image into the `contents/` subdirectory rather than using the dev UI.

**Comment by xlotlu** [comment]
This could be resolved along with #344.

**Comment by xlotlu** [comment]
This has been closed, but half of the problem has in fact not been fixed, one still can't keep slugify's hands off of hand-crafted `_slug`s. I mentioned this under https://github.com/lektor/lektor/issues/806.
