### ISSUE TITLE
lektor 3.2.0 requires Werkzeug<1, but you'll have werkzeug 1.0.1 which is incompatible

### ISSUE THREAD

**Issue by jdeibele** [lektor/lektor#829]
Doing updates and this popped up.  I don't see it addressed in issues or pull requests.

**Comment by runfalk** [comment]
Not sure I understand what you're saying. We require `werkzeug<1` in the `setup.py`. Now, I don't think Lektor actually has any problems with running using Werkzeug 1.0.1 (just tested it locally). IIRC that `<1` originates because of compatibility with [lektor-atom](https://github.com/lektor/lektor-atom). Removing the `<1` constraint should be fine now that lektor-atom no longer depends on werkzeug (https://github.com/lektor/lektor-atom/pull/31).

**Comment by jdeibele** [comment]
I run pip-review which updates installed packages.  It was flagging Lektor because it was requiring Werkzeug less than 1.0. It's great if Lektor will work without that dependency.   Thank you for looking into it.

**Comment by arabidopsis** [comment]
Yes I'm running lektor with werkzeug > 1. There isn't a problem with Lektor as far as I can tell but....

The subprocess  library in versions of python I'm using  3.7+ are now giving annoying resource warnings about open file
descriptors when you cntrl^C.

Since Werkzeug>1 transfers an open socket from the foreground to the background using socket.fromfd (or something)
(at least on *nix) I'm suposing this is the issue. It allows the socket to remain open during reloads but
confuses the subprocess library somehow about a resource leak.

Anyhow ... might worry some users... worried me for a bit too.

**Comment by thrimbor** [comment]
If Werkzeug is indeed not required anymore, I think it would be best to push out a small release that drops this dependency. Just to make the life of downstream packagers easier.

**Comment by runfalk** [comment]
Werkzeug is definitely still required. Apart from being used by Lektor it's a direct dependency of Flask (and Lektor uses Flask). We don't have the desire to remove the Werkzeug dependency either.

```
$ rg werkzeug lektor/
lektor/db.py
17:from werkzeug.urls import url_join
18:from werkzeug.utils import cached_property

lektor/publisher.py
13:from werkzeug import urls

lektor/devserver.py
6:from werkzeug.serving import run_simple
7:from werkzeug.serving import WSGIRequestHandler

lektor/buildfailures.py
6:from werkzeug.debug.tbtools import Traceback

lektor/context.py
4:from werkzeug.local import LocalProxy
5:from werkzeug.local import LocalStack

lektor/builder.py
15:from werkzeug.posixemulation import rename

lektor/utils.py
32:from werkzeug import urls
33:from werkzeug.http import http_date
34:from werkzeug.posixemulation import rename
35:from werkzeug.urls import url_parse

lektor/environment.py
13:from werkzeug.urls import url_parse
14:from werkzeug.utils import cached_property

lektor/markdown.py
7:from werkzeug.urls import url_parse

lektor/reporter.py
7:from werkzeug.local import LocalProxy
8:from werkzeug.local import LocalStack

lektor/project.py
6:from werkzeug.utils import cached_property

lektor/admin/modules/__init__.py
1:from werkzeug.utils import find_modules

lektor/admin/modules/common.py
8:from werkzeug.utils import cached_property

lektor/admin/modules/serve.py
12:from werkzeug.datastructures import Headers
13:from werkzeug.exceptions import NotFound
14:from werkzeug.wsgi import wrap_file

lektor/admin/modules/dash.py
8:from werkzeug.wsgi import extract_path_info

lektor/admin/webui.py
8:from werkzeug.utils import append_slash_redirect
```

**Comment by thrimbor** [comment]
I meant the `<1` part, not Werkzeug as a whole. Sorry for being unclear.
