### ISSUE TITLE
Cannot generate links to pages in template that stay in alternative (translation)

### ISSUE THREAD

**Issue by dwt** [lektor/lektor#866]
I have a macro like this:

```jinja
{% macro render_category_nav(active=none) %}
  <ul>
  {% for category in site.query('/categories') %}
    <li{% if category._id == active %} class="active"{% endif
      %}><a href="{{ category|url }}">{{ category.title }}</a></li>
  {% endfor %}
  </ul>
{% endmacro %}
```

The problem with this is, that the links to the categories always point to the main language/alternative. I.e. `{{ category|url }}` will not generate a url to the current alternative, but always to the main language.

**Comment by runfalk** [comment]
I have never actually used alternatives so I can only give you hints. I think this is because you are querying `/categories` without providing an `alt` (language). If you look at the API (https://www.getlektor.com/docs/api/db/pad/query/) there is a second parameter which defaults to `_primary`. That should be the language. I assue the labels themselves are also not in the correct language?

I think you can access the current page's alt using `this._alt` (https://www.getlektor.com/docs/api/db/system-fields/alt/). Id try this:

```jinja2
{% macro render_category_nav(alt, active=none) %}
  <ul>
  {% for category in site.query('/categories', alt) %}
    <li{% if category._id == active %} class="active"{% endif
      %}><a href="{{ category|url }}">{{ category.title }}</a></li>
  {% endfor %}
  </ul>
{% endmacro %}
```

Then use it like

```jinja2
{{ render_catectory_nav(this._alt) }}
```

**Comment by dwt** [comment]
This is quite helpful.

This is what I have settled on:

```jinja
{% macro render_category_nav(this, active=none) %}
  <ul>
  {% for category in site.query('/categories', alt=this.alt) %}
    <li{% if category._id == active %} class="active"{% endif
      %}><a href="{{ category|url }}">{{ category.title }}</a></li>
  {% endfor %}
  </ul>
{% endmacro %}
```
