### ISSUE TITLE
bug in _build_parent_path function

### ISSUE THREAD

**Issue by odeckmyn** [lektor/lektor#895]
https://github.com/lektor/lektor/blob/5a2895c1b683c1df98beed2ad970f8ebdab26a75/lektor/sourcesearch.py#L61

In this function, the info object can be None, but `info['path']` is used before checking ! This happened in one of my plugins. 

```
def _build_parent_path(path, mapping, alt, lang):
    rv = []
    for parent in _iter_parents(path):
        info = _find_best_info(mapping.get(parent) or [], alt, lang)
        id = _id_from_path(info['path'])
        if info is None:
            title = id or '(Index)'
        else:
            title = info.get('title')
        rv.append({
            'id': id,
            'path': parent,
            'title': title
        })
    return rv
```

See https://stackoverflow.com/questions/66389221/a-lektor-website-unable-to-build-twice-in-a-row for my own case, but it should'nt really matter as the function seems buggy whatever my plugin :-)

Here is a fix we could use ?

```
def _build_parent_path(path, mapping, alt, lang):
    rv = []
    for parent in _iter_parents(path):
        info = _find_best_info(mapping.get(parent) or [], alt, lang)
        if info is None:
            id=''
            title = '(Index)'
        else:
            id = _id_from_path(info['path'])
            title = info.get('title')
        rv.append({
            'id': id,
            'path': parent,
            'title': title
        })
    return rv
```
 
What do you guys think ?

**Comment by dairiki** [comment]
The current code is definitely screwy — clearly `info` will never be `None` at that `if` statement.

I wonder, though, why this isn't causing trouble for anyone else, though.  Clearly `info = None` must not happen very often, or we would hear more complaints.

Before committing this "peephole fix", it would be good to suss out whether `info = None` is even a valid state, or whether that's an indication, perhaps, of some other bug.

Can you shed any more light on the significance of `info = None` in your case?

**Comment by dairiki** [comment]
So, having dug into things a big more...

Having grokked what is going on in `lektor.sourcesearch` a bit better, I *think* this is a real bug (which is not currently exercised by current Lektor usage) and the correct fix is to change:
```python
        id = _id_from_path(info['path'])
```
to
```python
        id = _id_from_path(parent)
```

(We want the "id" or "basename" of the parent.  In any case, all of the `info`s in `mapping.get(parent, [])` (if there are any) are guaranteed to have `info["path"] == parent`.)

----

As far as the current Lektor code goes, `lektor.sourcesearch.find_files` is only called from once place, that is `lektor.builder.Builder.find_files`.  That method, in turn, is only called from one place in `lektor.admin.modules.api` in order to implement the `/admin/api/find` method of the admin API.  (That is used by the "Find Files" dialog, accessed by clicking the magnifying glass in the admin GUI.)

![image](https://user-images.githubusercontent.com/495018/109439988-6857fa80-79e5-11eb-9097-18add1d1f091.png)

As the docstring for [`build.find_files`][1] says:

> Returns a list of files that match the query.  This requires that the source info is up to date and is primarily used by the admin to show files that exist

This brings up the question as to why `builder.find_files` is being called from your plugin at all.
`Find_files` is really meant to be a fast global search for the admin GUI.  The returned results are not guaranteed to always be complete or correct, as they come solely from the "source info" database (which may be missing or incomplete at times) and are not checked against the `contents` tree.  (This probably explains why you do not see the exception on your initial build, but only on subsequent builds.  I suspect the results of your call to `build.find_files` are incomplete on the first build and do not include the result that is triggering the exception.)

I'm guessing your plugin is calling `builder.find_files` to find all attachments on your site.   I don't think this is the right way to do that.  (There may well be a better way to accomplish your goal than iterating over all attachments anyway, but I can't really say without knowing more about what the plugin is trying to do.)

[1]: <https://github.com/lektor/lektor/blob/5a2895c1b683c1df98beed2ad970f8ebdab26a75/lektor/builder.py#L1116>
