### ISSUE TITLE
pagination not taken into account in Query's _iterate

### ISSUE THREAD

**Issue by bbbart** [lektor/lektor#907]
Hi,

I'm quite stunned by the following problem. I one of my block templates, I'm going through the following process:

    {% set data = site.get('/data/' ~ this.datapage) %}
    {% for post in data.pagination.items %}
     ...
    {% endfor %}

I let the user select their own datapage, defined in the model as `type=select` and `source=site.get('/data').children`.

Everything seems to work just fine, except that the pagination.items-loop goes over **all** the children.

I did a lektor build with some breakpoints added to the source, and figured out the following:
 - the `@cached_property pagination` of the `Record` object contains four items (as defined through the `per_page` model configuration)
 - the `@property items` of the `Pagination` object also contains the four correct items
 - the `iter_child_sources` method of the `PageBuildProgram` also contains a correct `Query`, returning four items
 - however, the `__iter__` method in `Query` ruins it all, by calling `self._iterate` which simply returns an iterator over all the children, instead only those of a page

Without having intimate knowledge of the code, it seems to me that this is because the `_matches` method doesn't take pagination into account, neither directly, neither through `_filters`.

I'm confused however, since in other, earlier projects I have pagination working just fine.

Is this a regression? Or has this to do with my getting to the data `Record` through the site `Pad`?

**Comment by dairiki** [comment]
I'm a bit confused as to what you're trying to do (and what result you're expecting.)

```html+jinja
{% set data = site.get('/data/' ~ this.datapage) %}
```

So, `data` is now the record corresponding to `/data/`_datapage_, with no explicit page number.  I.e. `data.page_num` is `None`.

Normally, `data.pagination.items` yields a slice of the children of `data` corresponding to page `data.page_num`.  Since `data.page_num` is `None`, it returns all the children.

To get a particular page's slice of the children,  try `data = site.get('/data/' ~ this.datapage, page_num=n)`.

(Normally, when rendering a paginated page, the page template is invoked once for each page.  The first invocation has `this.page_num = 1`, the second has `this.page_num = 2`, etc.   In your case, when fetching the record for some other page, to get paginated results, one needs to be explicit about which page is wanted.)

**Comment by bbbart** [comment]
Ah, this makes a lot of sense, I'll try this.  Thanks a lot.

Some more context:

I'm building a fairly large website in Lektor, with identical content coming back in one form or another on different pages on the website. This is why I have defined some content as 'pages' and some as 'data'. All flowblocks and models have a `datapage` field where the content writer can attach a related dataset to the page or block.

In this fashion, content only has to be defined once, even though it gets repeated across the website at different locations.

All was working fine, until I came across some content that needed pagination. I believe your comment will help me further however.

Thanks again!
