### ISSUE TITLE
Custom css file inconsistent behavior during deployment 

### ISSUE THREAD

**Issue by Jeroendevr** [lektor/lektor#908]
Currently I use the [Resumé](https://github.com/hannylicious/lektor-theme-resume/tree/e2c32d5a4ab877fa6029a0b2e3edb13d6425afab) theme. I created a copy of the `resume.min.css` file in the `assets/css` folder. Here I change a color value for a certain property. When running locally `lektor server` the changed behavior of the color is visible in the `/admin/` interface. But when deploying locally to a folder the css color from the theme is used. Somehow my own values are being override by the theme value during build. 

The curious thing is that when I _remove_ the property theme property is not used. So it's not entirely inconsistent. I did not worked out the cases for other changes.

**Comment by sha016** [comment]
I bumped into this as well when attempting to override parts of a theme (https://www.getlektor.com/docs/themes/customizing/). The issue appears to be because both `/assets` and `/themes/sometheme/assets` get added to the `to_build` queue, and both get written to the output dir (visible with -v on a build). The theme asset (in my case "style.css") looks like it's getting written second, which "overrides the override". I believe the intended behavior is for files in `/assets` to take precedence over `/themes/sometheme/assets`. In my initial testing this only occurred with a `assets/static/style.css` file and not a `templates/index.html` template. @dairiki i'm not familiar with the project yet but maybe I could open a PR to fix this?

**Comment by dairiki** [comment]
The *theming support* is the one part of Lektor that I have not played with at all.

From a quick look, it does look like the current code does what you say. Essentially it copies everything in any of the `asset` directory trees to the output, so if there are identically named assets in the theme and in the site, one will overwrite the other.  I haven't yet sussed out what determines the order of the copying.

The proper fix is to make sure that only one of the conflicting assets gets copied, but I'm not quite sure the best way to do that.  I think the fix probably involves modifying [DirectoryAssetBuildProgram.iter_child_sources](https://github.com/lektor/lektor/blob/7b6c381e16cfceaad16d53f01a1013b666f63d60/lektor/build_programs.py#L275-L276) so that it omits any children that are shadowed by a higher priority asset tree.  I will look at it further when I get the chance.

----

#### A Workaround

For the time being, the workaround is probably to avoid having assets with identical names.

An option for CSS files would be to have your HTML template reference both `resume.min.css` from the theme assets and a `site.css` from the site assets.  Then you can place overrides for colors (or whatever) in `site.css`.

**Comment by dairiki** [comment]
@sha016 If you get the chance, try PR #1147 to verify that it fixes the issue.

**Comment by sha016** [comment]
@dairiki I've pulled your branch and ran `lektor build`. My css file is now overriding the theme's css file. Thanks for your attention on this!

**Comment by dairiki** [comment]
#1147 has been merged to the master branch and [pre-release] 3.4.0b8.

Let me know if there's a strong desire to have this back-ported to the 3.3.x branch. 

[pre-release]: https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions

**Comment by Jeroendevr** [comment]
I'll have to update lektor no problem. Thanks for solving the issue.
