### ISSUE TITLE
Change recomended installation method to `pipx`

### ISSUE THREAD

**Issue by andoresuperesu** [lektor/lektor#915]
I've installed `lektor` multiple times to test and contribute to Barranquilla's python community page pybaq.co and my personal page. I've also attempted to teach others how to install it (mostly beginners) with various barriers in the process.

On some versions of ubuntu there are issues with availability of wheels for some packages. On windows there are issues when using python from the Windows Store. Many of these issues arise from trying to build everything from scratch.

I propose the use of `pipx` to create an easier install. It is [recommended by PyPA](https://packaging.python.org/guides/installing-stand-alone-command-line-tools/) specifically for stand alone command line tools. It is OS independent. It is part of [PyPA's codebase](https://github.com/pypa/pipx). It has [clear documentation](https://pypa.github.io/pipx/).

After basic installation, `lektor` install script would be as simple as `pipx install lektor` or adding `sudo pipx install lektor` for ubuntu based distributions to perform a global install.

Are there argument in favor or against? I'd take the task to update the docs on the webpage if agreed upon. (And of course, #911 has to be included for any install to work correctly without the need for alternate procedures).

**Comment by dairiki** [comment]
As a user of Lektor on Debian and Ubuntu systems, I say +1.  This is, already, how I typically install Lektor.

I can not speak to what the `pipx` experience is like on Windows or Mac, but assuming that it works without requiring contortions, it seems like it would be the way to go.

**Comment by andoresuperesu** [comment]
I've so far tested the pipx experience on Ubuntu and Windows with success; pending the test on Mac and Windows store Python installation method.

**Comment by yagebu** [comment]
I'd also be very much in favor of moving away from the current install script, since it just seems to be full of bugs judging from the number of issues related to it. I've actually always just done regular pip installs in virtual environments, but `pipx` seems like exactly the right tool for this :)

**Comment by andoresuperesu** [comment]
@dairiki @yagebu @runfalk @nixjdm 

I must ask since I've gotten nowhere searching specific decisions on other related topics:

 - Where do we stand on Python 2.7 support? Its said to be supported on [docs/installation](https://www.getlektor.com/docs/installation/). PipX only works on python 3.6+
 - Would there be an issue if PipX doesn't support system-wide installation of Lektor? It seems purposely built to avoid system wide installs (might be wrong).

**Comment by dairiki** [comment]
> * Where do we stand on Python 2.7 support? Its said to be supported on [docs/installation](https://www.getlektor.com/docs/installation/). PipX only works on python 3.6+

The `master` branch of Lektor dropped support for python<3.6 [some time ago](https://github.com/lektor/lektor/pull/819), so once we get a new release of Lektor (and corresponding update to the docs) that is not an issue.

**Comment by dairiki** [comment]
> * Would there be an issue if PipX doesn't support system-wide installation of Lektor? It seems purposely built to avoid system wide installs (might be wrong).

I'm not sure how important supporting site-wide installs is.  (Personally, I could care less.)

The [current install script](https://github.com/lektor/lektor-website/blob/101aef6bf2a5d54cddecc634a9ddd125fb9e60f9/assets/installer.py#L237) seems to support it (when run as root), but does some sort-of-scary-looking auto-selection regarding which directory to install into based on what's in `$PATH`.  IMO, this seems like a bad idea.  I think site-wide installs should require the user to be pretty explicit about where things are being installed.

It does appear that `pipx` can be used to perform site-wide (i.e. usable by all users) installations via manipulation of the `$PIPX_HOME` and `$PIPX_BIN_DIR` environment variables.

E.g. something like this (run as root) will result in a working `/opt/pipx_bin/lektor`:
```sh
export PIPX_HOME=/opt/pipx
export PIPX_BIN_DIR=/opt/pipx_bin
pipx install lektor
```

I tested this in a cursory manner and it seems to work (not that there might not be things that could go wrong.)

**Comment by andoresuperesu** [comment]
@dairiki Thank you for the clearing of both things.

I've been testing many installation options as I write a quick update to the install instructions. I do not have any  OS X device for testing at the moment (asking for little time on one to test this).

Here's what I've written so far, [at least the gist of it](https://gist.github.com/andresperezcera/abf5ada9eab1dacff4d698ee7bc8151f).

**Comment by dairiki** [comment]
> Here's what I've written so far, [at least the gist of it](https://gist.github.com/andresperezcera/abf5ada9eab1dacff4d698ee7bc8151f).

Looks good!

A question for others is whether we want to continue to mention the (no longer supported) Mac Desktop app.  (I say probably not.)

A couple of notes/thoughts:

### Typo

There's a typo: "Ubuntu" not "Ubunto". :-)


### Pipx is packaged in many distributions

All releases of [Ubuntu](https://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=pipx) from 20.04 (focal) onward have a `pipx` package (that can be directly installed using `apt`.)
Debian Buster (oldstable) has one, too, though Debian Buster (stable) [does not](https://packages.debian.org/search?searchon=names&suite=all&section=all&keywords=pipx) (though there is one in buster-backports.)
(I can't help you with Windows or Mac...)

### Are the *-dev packages required these days?

I did a quick test in a docker container running [`ubuntu:focal`](https://hub.docker.com/_/ubuntu?tab=tags&page=1&ordering=last_updated&name=focal).  (This is a pretty lean base installation.)  To successfully install Lektor all that was necessary was:
```sh
apt update
apt install python3-venv pipx
pipx ensurepath
pipx install lektor
```
This did not pull in any -dev packages. The only binary wheel installed was for `MarkupSafe` for which a [fairly complete](https://pypi.org/project/MarkupSafe/2.0.1/#files) set of binary wheels appears available.

In a [`debian:bullseye-slim`](https://hub.docker.com/_/debian?tab=tags&page=1&ordering=last_updated&name=bullseye) container (so no `pipx` package) the following seemed to be about the minimal necessary script:
```sh
apt update
apt install --no-install-recommends python3-pip python3-venv
python3 -m pip install --user pipx
~/.local/bin/pipx ensurepath
. ~/.profile
pipx install lektor
```

Of course, `imagemagick` would be required for thumbnail support to work.  Also `ffmpeg` for video thumbnailing, and `git` for the *ghpages* publisher.

### Why is installation via pip in a virtualenv "heavily discouraged"?

The [current installation instructions](https://www.getlektor.com/docs/installation/#pip) say this is possible then say it is discouraged.

From what I can tell, most of the active developers install Lektor this way for daily use.  I would hope this will be supported.

Given the current state of the install script, this seems to be the only way that works right now...
If we do move to recommending `pipx`, that also would tend to require that installation via pip is supported (since that's, essentially, what pipx does.)

I think we should remove the “heavily discouraged” language from the docs.  Or — if for some reason we’re still serious about discouraging it — we should just remove that section altogether.  It’s just confusing to say: "You can do this... but don't!"

**Comment by andoresuperesu** [comment]
@dairiki Those were really good points.

About the desktop app I removed basically all references in the gist because the single referenced issue is now closed with a build apps for all platforms issue with little progress at the moment. A lot has been stated at #760 but nothing concrete. 

About requirements: I removed most of it. I guess package managers tend to warn with pretty straightforward
 messages if anything additional is needed. I tried to go for clear informal language above rather than covering all that's possible. 

__About the pip install:__ I guess when Lektor started virtual environments were somewhat a mess to learn with many competing ways to go about them and a huge chance to get confused and mess everything up. I make it clear, Back then. Now... this has changed. Even newcomers to python would usually install everything through pip and later realize they need to clean their installed packages; just then they'd move everything into venvs. __I removed the scaremongering language.__ The bold part is the important one.

Again: [The Gist](https://gist.github.com/andresperezcera/abf5ada9eab1dacff4d698ee7bc8151f)

**Comment by dairiki** [comment]
@andresperezcera  Your gist looks great to me.  (Hopefully, those with the release keys will agree!)
One suggestion: add a link to the [pipx installation docs](https://pypa.github.io/pipx/installation/).

**Comment by dairiki** [comment]
If we do away with the installer script, the text at https://www.getlektor.com/downloads/ (which is the target of the "Download 3.2.0" link at getlektor.com) will need to be rejiggered, too... :-/

**Comment by andoresuperesu** [comment]
Oh, yessss, the second file in the gist is precisely that. Sorry I didn't explicitly clarify that. I'll proceed to do the pull request.

**Comment by dairiki** [comment]
Aha!  I did miss that.

Maybe we no longer need two pages ("Download" and "Docs/Installation") that contain, essentially, the same information...

As an aside: Clearly, in past years, there was a real motivation to make installation of Lektor as simple as possible — a single-file app.  Is that still a goal?  Times have changed — virtualenvs, pipx, etc. have become  more mainstream. Anyway, by now we've probably lost any users that would really benefit from a single-file app...

**Comment by andoresuperesu** [comment]
I'd still vouch for simplicity because many python groups/meetups have taken Lektor as a python related webpage creating tool to foster involvement (at least that seems to be the case in Colombia). However the idea that beginners would easily contribute to such webpages seems to have been a fantasy and far from reality. Furthermore, most contributors or issue authors mention hosted cases that escape simple installations (See #665, #460 and #745). So, accommodating more complex use cases seems to be the way.

Although it departs from the original purpose &mdash; that of creating a simple app to help Armin's parents update their webpages &mdash; it seems to better serve that purpose to more users through a single developer when pointing towards hosted Lektor. Perhaps this is a discussion belonging to another issue. Lektor Future, perhaps?
