### ISSUE TITLE
DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'.

### ISSUE THREAD

**Issue by animeshkrishnabulusu** [lektor/lektor#928]
I am seeing this error newly when I run `lektor build` after a 'lektor clean`.

DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.

This is the line where this warning is thrown at:

```
{% set siblings = post.get_siblings() %}
```

I just upgraded to python 3.9.6 and the lektor version remained at 3.2.0

**Comment by dairiki** [comment]
This warning comes about when running with the latest version `MarksupSafe` (`>=2.0`) but an old version of `Jinja2<3.0`.

When performing a clean install of Lektor 3.2.0 (using the latest pip==21.2.4), due to Lektor’s pin of `Werkzeug<1`, one winds up with `Flask==1.1.4` (more recent Flasks require `Werkzeug>=2`).  `Flask==1.1.4`, in turn, pins `Jinja2<3.0`.

The (unreleased) version of Lektor in the `master` branch has removed the `Werkzeug<1` (and now explicitly pins `Jinja2>=3`), so it will run with the latest released versions of Jinja2, MarkupSafe (& Flask & Werkzeug).

====

It is just a warning, so it is safe, I think, to ignore it.  If you want to get rid of it when running Lektor=3.2.0, I think that manually pinning `MarkupSafe<2` should work.  E.g. install Lektor in your virtualenv with something like this:
```sh
pip install Lektor 'MarkupSafe<2'
```

**Comment by animeshkrishnabulusu** [comment]
That is fair enough. Thank you for the quick response. 

I will wait for the next release then. If needed, I will try the fix of pinning specific version of MarkupSafe.

I don't mean to rush you, but I would like to know if you have decided on a tentative timeline for a next release on the changes in `master`. Going through the recent issues, I can see some issues have been addressed in `master`. So it would be great to know if you do have something in mind. 

Regards.

**Comment by dairiki** [comment]
> I don't mean to rush you, but I would like to know if you have decided on a tentative timeline for a next release on the changes in `master`.

I am just a contributor, so I have no power to make a release, but I agree: It's past time for a 4.0 release.  The last release was a year ago and there have been 320 commits on the master branch since then.  I would argue for a much more rapid release cycle — with releases made whenever bugs are fixed or features are added.

On a related note, the documentation page could use some love.  There are a number of doc PRs that could use some attention, and it's been a while since the website has seen an update.

**Comment by animeshkrishnabulusu** [comment]
Agreed and understood.

This project is too awesome to not see a release sooner. I wish I could help, but I am not aware of all the complexities of a Python project deployment yet. Hoping for the best.
